### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by cliffburdick** [codyogden/killedbygoogle#1009]
**What's the Product's Name?**
Gallery

**Describe the product in a single sentence.**
Gallery is a simple, streamlined app that makes it easy to collaborate on product designs. 

**When was the product launched? Provide a specific date, if possible.**
May, 2018

**When was the product discontinued? Provide a specific date, if possible.**
December 16, 2021

**What type of product was it? App, Service, or Hardware?**
Service

https://support.google.com/materialgallery/answer/11044972?hl=en&ref_topic=11045865

**Comment by codyogden** [comment]
This is on the list as "Material Gallery." #1010
