### ISSUE TITLE
Android Browser

### ISSUE THREAD

**Issue by upintheairsheep** [codyogden/killedbygoogle#1057]
**What's the Product's Name?**
Android Browser
**Describe the product in a single sentence.**
It was a browser for android like safari. It was replaced by chrome. It started getting removed on Lollipop, but Nougat COMPLETELY killed it. The browser was there since the m3-rc20a and earlier!
**When was the product launched? Provide a specific date, if possible.**
2007
**When was the product discontinued? Provide a specific date, if possible.**
When Nougat launched
**What type of product was it? App, Service, or Hardware?**
App

**Comment by codyogden** [comment]
If you can find a link that describes this browser in more detail (specs, etc), I will reopen. Thanks!
