### ISSUE TITLE
Android Dessert Names

### ISSUE THREAD

**Issue by upintheairsheep** [codyogden/killedbygoogle#1058]
**What's the Product's Name?**
Dessert Names
**Describe the product in a single sentence.**
They were a unique marketing name for android and iconic. They were killed to make it “around the world”.
**When was the product launched? Provide a specific date, if possible.**
Android 1.5 Cupcake
**When was the product discontinued? Provide a specific date, if possible.**
Android 10 Queen Cake (was gonna be called that)
**What type of product was it? App, Service, or Hardware?**
???

**Comment by codyogden** [comment]
Thanks! I don't think anyone would consider these a product. Appreciate the suggestion though.
