### ISSUE TITLE
Google Toolbar for Internet Explorer

### ISSUE THREAD

**Issue by tech234a** [codyogden/killedbygoogle#1070]
**What's the Product's Name?** Google Toolbar for Internet Explorer

**Describe the product in a single sentence.** Integrated Google features into Internet Explorer.

**When was the product launched? Provide a specific date, if possible.** 2000-12-11

**When was the product discontinued? Provide a specific date, if possible.** Sometime between 2021-12-02 and 2021-12-12

**What type of product was it? App, Service, or Hardware?** Probably would be considered an app

[Article describing the shutdown](https://arstechnica.com/gadgets/2021/12/happy-21st-birthday-to-google-toolbar-which-inexplicably-still-exists/ )

[Announcement page that appears when trying to go to the landing page](https://support.google.com/toolbar/answer/81376)

**Comment by codyogden** [comment]
Thanks. Added in #1072.

**Comment by tech234a** [comment]
Small nitpick: the Firefox version of Google Toolbar was separately discontinued [in 2011], and already has a separate entry on the site.

[in 2011]: https://googletoolbarhelp.blogspot.com/2011/07/update-on-google-toolbar-for-firefox.html
