### ISSUE TITLE
Is Angular REALLY dead?

### ISSUE THREAD

**Issue by TechStudent11** [codyogden/killedbygoogle#1079]
I remember hearing so much about it (people using it for projects, etc.) and now I see on Killed By Google.

**Comment by metoule** [comment]
Angular is not dead, AngularJS is.

Confusingly, Angular and AngularJS are not the same product. AngularJS is the ancestor of Angular: AngularJS = Angular 1.x or Angular = AngularJS 2.x.

The main difference is that AngularJS is written in Javascript, while Angular is written in Typescript. Wikipedia has an entire section on the [differences between the two](https://en.wikipedia.org/wiki/Angular_(web_framework)#Differences_between_Angular_and_AngularJS).

Google used to maintain both versions, but they decided to only support Angular going forward.

**Comment by TechStudent11** [comment]
Ohhhhh that's really confusing. Thanks for clearing that up. The Angular page is still up and that really confusing.
