### ISSUE TITLE
Google G Suite Legacy (Free Accounts)

### ISSUE THREAD

**Issue by nicko170** [codyogden/killedbygoogle#1101]
**What's the Product's Name?**
G Suite Legacy

**Describe the product in a single sentence.**
Googles hosted email service

**When was the product launched? Provide a specific date, if possible.**
2012?

**When was the product discontinued? Provide a specific date, if possible.**
1 May 2022
https://support.google.com/a/answer/60217

**What type of product was it? App, Service, or Hardware?**
Service

**Comment by codyogden** [comment]
Being added in #1100.

Thanks!
