### ISSUE TITLE
Incorrect English grammar of plural "years" after a single year: "1 years ago"

### ISSUE THREAD

**Issue by RoryDuncan** [codyogden/killedbygoogle#112]
![image](https://user-images.githubusercontent.com/766828/47271774-3ab73880-d531-11e8-8f54-244d28dbec4c.png)

Seems this is returned from the `date-fns` `formatDistance` utility.

Maybe it needs to be specified to use the United States english locale?
 I see in [date-fns master](https://github.com/date-fns/date-fns/blob/master/src/locale/en-US/_lib/formatDistance/index.js#L54-L57) the `en-US` locale should display correctly... I haven't compared versions to see if a update would fix this. 🤔

**Comment by Synsyxx** [comment]
Fairly new to this sort of stuff, but if I'm understanding it right, should just need to replace 111 with formatDistance? Or maybe distanceInWords? Just reading over the docs for date-fns to try to understand how it works.

**Comment by codyogden** [comment]
@Synsyxx You've got it. Using `formatDistance` inside of Line 111, and taking out the word "years" would do it!

**Comment by Jeff-Duke** [comment]
PR open for this: https://github.com/codyogden/killedbygoogle/pull/116

**Comment by codyogden** [comment]
Closed in #116
