### ISSUE TITLE
Google Stadia

### ISSUE THREAD

**Issue by ahmeij** [codyogden/killedbygoogle#1125]
**What's the Product's Name?**
Stadia

**Describe the product in a single sentence.**
Stadia is Google's gaming platform that lets you instantly play video games on screens you already own. Stream games directly to your favorite compatible devices. They're ready wherever you have internet, without waiting for installs, downloads, or updates.

**When was the product launched? Provide a specific date, if possible.**
November 19, 2019 

**When was the product discontinued? Provide a specific date, if possible.**
https://www.businessinsider.com/google-stadia-stream-plan-partnerships-peloton-bungie-gaming-service-2022-2?international=true&r=US&IR=T
To be announced

**What type of product was it? App, Service, or Hardware?**
Service

**Comment by codyogden** [comment]
We only add products once an official announcement has been made. Thanks!
