### ISSUE TITLE
Hitchhiker

### ISSUE THREAD

**Issue by aubymori** [codyogden/killedbygoogle#1166]
**What's the Product's Name?**
Hitchhiker
**Describe the product in a single sentence.**
YouTube's older website design.
**When was the product launched? Provide a specific date, if possible.**
December 2012
**When was the product discontinued? Provide a specific date, if possible.**
Septermber 2021
**What type of product was it? App, Service, or Hardware?**
Service

Additional notes: The vast majority of Hitchhiker pages (home, watch, channel, results, etc.) became unavailable on Dec 14, 2020. September 2021 marks the removal of the attribution page which was the final Hitchhiker page to be removed.

**Comment by codyogden** [comment]
Hi there! 👋

Could you provide a source or some other link to help me understand Hitchhiker's significance? (archive.org?) Was this a product or just a design/design system?

Thanks!

**Comment by aubymori** [comment]
Well, Hitchhiker doesn't make sense but you could add the YouTube Creator Studio, which was killed in June 2020 IIRC.
