### ISSUE TITLE
Chrome Lite Mode (Data Saver)

### ISSUE THREAD

**Issue by TylerCarberry** [codyogden/killedbygoogle#1168]
**What's the Product's Name?**
Chrome Lite Mode

**Describe the product in a single sentence.**
Chrome Lite Mode (Data Saver) allowed users to save data on mobile by compressing websites server-side.

**When was the product launched? Provide a specific date, if possible.**
January 2014

**When was the product discontinued? Provide a specific date, if possible.**
March 29th, 2022

**What type of product was it? App, Service, or Hardware?**
Service?

https://support.google.com/chrome/answer/2392284?hl=en&co=GENIE.Platform%3DAndroid
https://www.androidpolice.com/google-is-retiring-chromes-data-saving-lite-mode-next-month-saying-its-no-longer-necessary/
https://support.google.com/chrome/thread/151853370/sunsetting-chrome-lite-mode-in-m100-and-older?hl=en

**Comment by codyogden** [comment]
Thanks for the suggestion. Closing, but see my comment in #1174 for more info.
