### ISSUE TITLE
"Honorable Mentions" category

### ISSUE THREAD

**Issue by upintheairsheep** [codyogden/killedbygoogle#1169]
Put an honorable mentions category for stuff that have been killed but was not a product. This should be the feature graveyard (from google photos unlimited uploads to old snakey). If you want you could add REAL PEOPLE  to honorable mentions who have been confirmed to be killed by an Android device (texting while driving, pokemon go, selfie injuries, smartphone zombie).

**Comment by codyogden** [comment]
There will be a space for this in the next couple of months, specifically a _Timeline of Events_ that will allow us to document major news, feature changes, deprecations, redesigns, etc. This also means we'll be able to track living an dead products on Killed by Google.

Closing this for now as it's already in the works. :)
