### ISSUE TITLE
Timer/Stopwatch (search widget)

### ISSUE THREAD

**Issue by wslack** [codyogden/killedbygoogle#1171]
**What's the Product's Name?**

No clear name; it was a widget popping up when people searched for "60 minute timer" or "stopwatch."

**Describe the product in a single sentence.**

Allowed easy timers and stopwatch function on web.

**When was the product launched? Provide a specific date, if possible.**

No idea.

**When was the product discontinued? Provide a specific date, if possible.**

In the last few days (feb 2022)

**What type of product was it? App, Service, or Hardware?**

Webapp

**Comment by codyogden** [comment]
Closing as this isn't dead. Still exists for me.

**Comment by wslack** [comment]
Huh, its back for me too! Thank you.
