### ISSUE TITLE
Google Assistant Snapshot

### ISSUE THREAD

**Issue by TylerCarberry** [codyogden/killedbygoogle#1172]
**What's the Product's Name?**
Google Assistant Snapshot

**Describe the product in a single sentence.**
Successor to Google Now that provided predictive information cards in the Google app for Android and iOS

**When was the product launched? Provide a specific date, if possible.**
July 2018

**When was the product discontinued? Provide a specific date, if possible.**
No date provided

**What type of product was it? App, Service, or Hardware?**
Service

https://www.droid-life.com/2022/03/03/googles-assistant-snapshot-is-going-away/
https://support.google.com/assistant/answer/11135696

**Comment by CyanoTex** [comment]
https://chromeunboxed.com/goodbye-google-assistant-snapshot
Adding another article.
