### ISSUE TITLE
Google Universal Analytics

### ISSUE THREAD

**Issue by pschneider87** [codyogden/killedbygoogle#1176]
**What's the Product's Name?**
Google Universal Analytics 

**Describe the product in a single sentence.**
Webanalytics Suite based on Urchin (RIP), used to track user behavior, revenues and campaign-performance on websites.

**When was the product launched? Provide a specific date, if possible.**
October 2012

**When was the product discontinued? Provide a specific date, if possible.**
01.07.2023

**What type of product was it? App, Service, or Hardware?**
Service

Link: https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/

**Comment by pschneider87** [comment]
any questions about this deprectation? I think the blogpost is pretty clear evidence

**Comment by LukasGrebe** [comment]
Diplicates #1378
