### ISSUE TITLE
Reverse Image Search

### ISSUE THREAD

**Issue by jonaheschwartz** [codyogden/killedbygoogle#1179]
Reverse image search

Search for sources containing an image in possession by user

2011

March, 2022

Service

**Comment by upintheairsheep** [comment]
Oh funk

**Comment by upintheairsheep** [comment]
I used that

**Comment by upintheairsheep** [comment]
They just replaced it with google lens for chrome

**Comment by ChildishGiant** [comment]
Reverse search is still alive and well?

**Comment by codyogden** [comment]
wut

<img width="855" alt="Screen Shot 2022-08-02 at 2 30 48 PM" src="https://user-images.githubusercontent.com/11383626/182458028-5db0e29d-cb99-4d6a-9feb-d55b8ec2c320.png">
