### ISSUE TITLE
Gboard minis emoji

### ISSUE THREAD

**Issue by VirusDumb** [codyogden/killedbygoogle#1221]
**What's the Product's Name?**
Google gboard minis
**Describe the product in a single sentence.**
Allowed you to make your custom emojis using a selfie to be used with Google's gboard keyboard.
**When was the product launched? Provide a specific date, if possible.**
August 2018
**When was the product discontinued? Provide a specific date, if possible.**
October 2021
**What type of product was it? App, Service, or Hardware?**
Service
**Links to sources**-https://9to5google.com/2021/09/28/gboard-minis-going-away-october/

**Comment by codyogden** [comment]
Hello! I appreciate the suggestion. After reviewing it, this doesn't quite fit a description of a product. It's a feature of Gboard that was removed. 😁
