### ISSUE TITLE
Legacy G Suite not going away

### ISSUE THREAD

**Issue by fialhorenato** [codyogden/killedbygoogle#1254]
Source: [Wired](https://www.wired.com/story/google-legacy-g-suite-account/#:~:text=Google%20posted%20an%20announcement%20in,it%20would%20ever%20be%20charged.)

**Comment by codyogden** [comment]
The product changed though, right? Like these accounts will no longer get new productivity services related to Google.

**Comment by fialhorenato** [comment]
@codyogden Weirdly nothing changed aside from support from Google, users will be able to keep the legacy version, as it was stated [here](https://www.wired.com/story/google-legacy-g-suite-account/#:~:text=Google%20posted%20an%20announcement%20in,it%20would%20ever%20be%20charged.), but only for personal use.

**Comment by kiltannen** [comment]
The G-Suite Legacy never did add new services, it was always a bit of an orphan anyway.

I really feel it deserves a Resurrection status.  Don't know if you have such a thing, but it is one of the ONLY times I recall Google cancelling something, and then bringing it back in effectively an unchanged form...

Maybe a Broken Gravestone icon?

Maybe a Phoenix Icon?

Please Help to signify it is still around!

**Comment by alanfranz** [comment]
Bump.

@codyogden I think it's not fair to say that the legacy G Suite was killed by google, since it's still 100% working for personal use.
