### ISSUE TITLE
YouTube achievements on Xbox One

### ISSUE THREAD

**Issue by TheBoxyBear** [codyogden/killedbygoogle#1257]
Not sure if this is appropriate and there is very little info on it

**What's the Product's Name?**
YouTube Xbox achievements

**Describe the product in a single sentence.**
The YouTube app for Xbox One featured Xbox Live achievements like many other apps on the console. Following many reports of achievement not unlocking, the app was delisted in 2017 and replaced with an identical app that had no achievements.

**When was the product launched? Provide a specific date, if possible.**
November 22, 2013

**When was the product discontinued? Provide a specific date, if possible.**
2017, around August 5th when the new app launched

**What type of product was it? App, Service, or Hardware?**
Service - The app still exists but is a clone of the original app with a missing feature.

**Comment by TheBoxyBear** [comment]
Sources
https://www.trueachievements.com/game/YouTube/achievements
https://www.microsoft.com/p/youtube/9ndp7ktlk7w3(launch date of the new app)

**Comment by codyogden** [comment]
See https://github.com/codyogden/killedbygoogle/pull/1258#issuecomment-1203050392
