### ISSUE TITLE
G Suite (Legacy Free Edition) has not been added to killedbygoogle.com yet

### ISSUE THREAD

**Issue by SmashedFrenzy16** [codyogden/killedbygoogle#1262]
**What's the Product's Name?**

G Suite (Legacy Free Edition)

**Describe the product in a single sentence.**

Was a non-commercial, free version of Google G Suite.

**When was the product launched? Provide a specific date, if possible.**

2006

**When was the product discontinued? Provide a specific date, if possible.**

May 2022

**What type of product was it? App, Service, or Hardware?**

Service

**Comment by codyogden** [comment]
![Screen Shot 2022-08-02 at 1 15 44 PM](https://user-images.githubusercontent.com/11383626/182445255-3784a1af-1acc-4c52-ac8d-f9c91af35b03.png)
