### ISSUE TITLE
@killedbygoogle twitter page suspended

### ISSUE THREAD

**Issue by wioxjk** [codyogden/killedbygoogle#1272]
https://twitter.com/killedbygoogle

![image](https://user-images.githubusercontent.com/10996038/184419648-ec8c1de9-34fe-43fd-bc33-71ceb089d7fc.png)

**Comment by codyogden** [comment]
Yeah. Am aware. People are targeting me with a false report.

**Comment by wioxjk** [comment]
That really sucks...
Maybe you can find a home at Mastodon?
https://joinmastodon.org/

There is plenty of instances that could work for you there.
