### ISSUE TITLE
Google Chrome Apps are not dead

### ISSUE THREAD

**Issue by Marko21552** [codyogden/killedbygoogle#1282]
It's not on the bookmarks anymore but if you type in chrome://apps on the url bar it will still work

**Comment by ExperiencersInternational** [comment]
I'm pretty sure Chrome Apps are completely similar to PWAs, which chrome://apps serves as a launcher for

**Comment by WebSnke** [comment]
Chrome Apps are dead. Period.

![image](https://user-images.githubusercontent.com/94064167/214857266-6166945f-87ed-49dc-8d5a-4223bb48e4a7.png)

**Comment by WebSnke** [comment]
This issue should be closed.
