### ISSUE TITLE
Google Survey

### ISSUE THREAD

**Issue by George-Miao** [codyogden/killedbygoogle#1284]
**What's the Product's Name?**
Google Survey

**Describe the product in a single sentence.**
Literally taking surveys for business customers

**When was the product launched? Provide a specific date, if possible.**
March 29, 2012

**When was the product discontinued? Provide a specific date, if possible.**
Dec 1, 2022

**What type of product was it? App, Service, or Hardware?**
Service

Link: https://support.google.com/surveys/answer/12626240

**Comment by grgarside** [comment]
Looks like there's two dates, which isn't confusing at all

From link above

> Google Surveys will no longer be available after November 1. As a result, Google Opinion Rewards for Publishers will also no longer serve new surveys on websites as of Dec 1.

and from the tool itself

<img width="628" alt="Screenshot 2022-10-02 at 8 52 06 am" src="https://user-images.githubusercontent.com/191085/193443871-eb1f3045-6927-4cd7-a4d7-760764b175a1.png">

**Comment by George-Miao** [comment]
> 

Lol typical
