### ISSUE TITLE
Google Stadia

### ISSUE THREAD

**Issue by thimslugga** [codyogden/killedbygoogle#1293]
**What's the Product's Name?**

Google Stadia

**Describe the product in a single sentence.**

Promo doc filler

**When was the product launched? Provide a specific date, if possible.**

2019

**When was the product discontinued? Provide a specific date, if possible.**

Winding down in 2022, shut down on 2023-01-18.

https://blog.google/products/stadia/message-on-stadia-streaming-strategy/

**What type of product was it? App, Service, or Hardware?**

Hardware + Service

__Originally posted by @thimslugga in https://github.com/codyogden/killedbygoogle/issues/444__

**Comment by SylveonBottle** [comment]
https://github.com/codyogden/killedbygoogle/pull/1287

**Comment by KotlinIsland** [comment]
The current listing doesn't link the blog post, it links to some article.

**Comment by SylveonBottle** [comment]
> it links to some article.

theverge.com is currently listed as the source for 8 other google products, so I believe it may be a reputable source according to the owner of this project.

That being said, if the blog post is the issue, you should instead create a pull request to change the link.

**Comment by flevanti** [comment]
This is a link to the official article.
https://blog.google/products/stadia/message-on-stadia-streaming-strategy/

While the announcement has been made sept 2022 the product will be retired/shut down jan 2023, don't know if that's relevant.
