### ISSUE TITLE
Driving-modus in Google Assistent

### ISSUE THREAD

**Issue by jaimevisser** [codyogden/killedbygoogle#1305]
**What's the Product's Name?**
Driving-modus in Google Assistent

**Describe the product in a single sentence.**
A driving focused mode to replace the defunct android auto interface.

**When was the product launched? Provide a specific date, if possible.**
2021

**When was the product discontinued? Provide a specific date, if possible.**
November 21st

**What type of product was it? App, Service, or Hardware?**
App

**Comment by epicbananana** [comment]
Wow, I wanted to write this but apparently I'm 7 hours late.
