### ISSUE TITLE
Youtube Dislike Counter

### ISSUE THREAD

**Issue by glxxyxafonso** [codyogden/killedbygoogle#1318]
**What's the Product's Name?**
The YouTube Dislike Counter
**Describe the product in a single sentence.**
Where you could see how many people disliked that video.
**When was the product launched? Provide a specific date, if possible.**
2005.
**When was the product discontinued? Provide a specific date, if possible.**
2022
**What type of product was it? App, Service, or Hardware?**
A part of YouTube, so I would consider it a Service.

**Comment by codyogden** [comment]
Thank you for opening the issue! This doesn't seem like a standalone product and more of a feature that is part of a wider product. Since we can't add features to the list, I'll close this.
