### ISSUE TITLE
What ever happened to Google Sketchup?

### ISSUE THREAD

**Issue by samjco** [codyogden/killedbygoogle#1326]
**What's the Product's Name?**
Google Sketchup

**Describe the product in a single sentence.**
3d Builder 

**When was the product launched? Provide a specific date, if possible.**

**When was the product discontinued? Provide a specific date, if possible.**

**What type of product was it? App, Service, or Hardware?**
Software

**Comment by codyogden** [comment]
SketchUp was sold to Trimble in 2012.

https://en.wikipedia.org/wiki/SketchUp
