### ISSUE TITLE
google web light

### ISSUE THREAD

**Issue by FONZACUS** [codyogden/killedbygoogle#1348]
**What's the Product's Name?**
Google Web Light
**Describe the product in a single sentence.**
is a service offered by Google for faster browsing within its Android mobile browser Chrome
**When was the product launched? Provide a specific date, if possible.**
2015
**When was the product discontinued? Provide a specific date, if possible.**
2022-12
**What type of product was it? App, Service, or Hardware?**
service

https://www.google.com/search?q=google+weblight
https://www.searchenginejournal.com/google-retires-web-light

i dont think the main site was ever archived

**Comment by WebSnke** [comment]
I just submitted a PR to resolve this issue.
