### ISSUE TITLE
Grasshopper

### ISSUE THREAD

**Issue by carloshbcabral** [codyogden/killedbygoogle#1360]
**What's the Product's Name?**
Grasshopper

**Describe the product in a single sentence.**
Grasshopper is an app that teaches users to code with JavaScript.

**When was the product launched? Provide a specific date, if possible.**
20 June 2017

**When was the product discontinued? Provide a specific date, if possible.**
15 June 2023

**What type of product was it? App, Service, or Hardware?**
App

https://support.grasshopper.app/t/grasshopper-is-shutting-down-on-june-15-2023/61994

**Comment by codyogden** [comment]
This is on the list.

https://github.com/codyogden/killedbygoogle/blob/485ea7e63a935f504316c5429b9fb8952200cd54/graveyard.json#L2267-L2274
