### ISSUE TITLE
Project Jacquard

### ISSUE THREAD

**Issue by meenbeese** [codyogden/killedbygoogle#1366]
**What's the Product's Name?**
Project Jacquard
**Describe the product in a single sentence.**
Used to embed things like touch sensors and haptic feedback into an article of clothing, which can then be paired with a smartphone.
**When was the product launched? Provide a specific date, if possible.**
2015
**When was the product discontinued? Provide a specific date, if possible.**
March 17, 2023
**What type of product was it? App, Service, or Hardware?**
App that is connected to hardware (clothes)

**Comment by meenbeese** [comment]
Complimentary news links:
https://9to5google.com/2023/03/17/google-shutting-down-jacquard-app/
https://www.androidpolice.com/google-project-jacquard-shutting-down/

**Comment by WebSnke** [comment]
Thanks, I just added a PR to resolve this issue.
