### ISSUE TITLE
Polymer?

### ISSUE THREAD

**Issue by Naleksuh** [codyogden/killedbygoogle#1368]
Polymer is listed as being killed in 2021, but YouTube still uses Polymer, and the link listed doesn't say anything about any death in 2021.

Is it confirmed to have any non-use, and if so should it be removed?

**Comment by codyogden** [comment]
"Non-use" isn't necessarily how something is decided as being killed. The docs list it as being [in maintenance mode](https://polymer-library.polymer-project.org/), and the [last release](https://github.com/Polymer/polymer/releases/tag/v3.4.1) was in 2020.
