### ISSUE TITLE
Google Analytics UA (Universal Analytics)

### ISSUE THREAD

**Issue by michaeljoelt** [codyogden/killedbygoogle#1378]
**What's the Product's Name?**
Google Analytics UA (Universal Analytics)

**Describe the product in a single sentence.**
Analytics tracking using session-based data with easy report/dashboard creation and the ability to set up scheduled e-mail subscriptions for them.

**When was the product launched? Provide a specific date, if possible.**
UA (Universal Analytics) as we know it started in 2013, but it began as "Urchin Analytics"(1995), which was purchased by Google in 2005.

**When was the product discontinued? Provide a specific date, if possible.**
July 2023

**What type of product was it? App, Service, or Hardware?**
Service

RIP UA (Replaced by GA4)

**Comment by LukasGrebe** [comment]
It’s dead :-( 
Why isn’t it on the site?

**Comment by pschaub** [comment]
Google decided that users will lose access to Universal Analytics data on July 1, 2024. I've created a new issue: https://github.com/codyogden/killedbygoogle/issues/1536
