### ISSUE TITLE
YouTube Stories

### ISSUE THREAD

**Issue by LinosTheDev** [codyogden/killedbygoogle#1391]
**What's the Product's Name?**
YouTube Stories
**Describe the product in a single sentence.**
A feature that mimicked Instagram Stories and allowed creators to post featured images and videos on their profile.
**When was the product launched? Provide a specific date, if possible.**
11/12/2018
**When was the product discontinued? Provide a specific date, if possible.**
6/26/2023
**What type of product was it? App, Service, or Hardware?**
Service

**Comment by CityIsBetter** [comment]
isnt this issue is already open in #1383
