### ISSUE TITLE
[Upcoming] Album Archive

### ISSUE THREAD

**Issue by Zeniic** [codyogden/killedbygoogle#1397]
**What's the Product's Name?**
Album Archive

Received an email about this one, also found info here: https://support.google.com/picasa/answer/7008270?hl=en-GB
OR https://cordcuttersnews.com/google-is-shutting-down-album-archive/

**Describe the product in a single sentence.**
Album Archive is a platform provided by Google that allows users to access and manage their archived photos and videos from various Google services, such as Google Photos and Picasa Web Albums.

**When was the product launched? Provide a specific date, if possible.**
March 30, 2016

**When was the product discontinued? Provide a specific date, if possible.**
Starting 19th July 2023

**What type of product was it? App, Service, or Hardware?**
Service

**Comment by erinfinn5** [comment]
Here's a news website I found!!
https://cordcuttersnews.com/google-is-shutting-down-album-archive/

**Comment by Zeniic** [comment]
Thanks @erinfinn5
Updated the Issue.

**Comment by Sembiance** [comment]
Confirmed. I got the following email:
![IMG_0641](https://github.com/codyogden/killedbygoogle/assets/81436/fc1e0333-98d5-4996-b24c-7ee8bf9315fd)

**Comment by Fusl** [comment]
Navigating to this web page also shows the notice: https://get.google.com/albumarchive/
![image](https://github.com/codyogden/killedbygoogle/assets/2349496/66e4beee-5cc1-461f-bacc-f01739a2ccf1)

**Comment by moom0o** [comment]
got the same email

**Comment by moom0o** [comment]
I created a pull request #1398

**Comment by moom0o** [comment]
Where did you get the launch date?

**Comment by moom0o** [comment]
pr has been merged, this can be closed now.
