### ISSUE TITLE
Add youtube rewind

### ISSUE THREAD

**Issue by BenjaminPro2215** [codyogden/killedbygoogle#1402]
Youtube rewind is something youtube (Owned by Google) did every year!
But then, people started hating it...
And it died!

R.I.P Rewind

2010 to 2019

**Comment by BenjaminPro2215** [comment]
Find more information here...
https://en.wikipedia.org/wiki/YouTube_Rewind

**Comment by codyogden** [comment]
Thanks for the suggestion. YouTube Rewind isn’t a product. It’s a marketing campaign.
