### ISSUE TITLE
Project Iris

### ISSUE THREAD

**Issue by ChaseKnowlden** [codyogden/killedbygoogle#1404]
**What's the Product's Name?**
Project Iris
**Describe the product in a single sentence.**
Project Iris was a AR headset that would compete with Meta and Apple.
**When was the product launched? Provide a specific date, if possible.**
01-20-2022
**When was the product discontinued? Provide a specific date, if possible.**
06-27-2023
**What type of product was it? App, Service, or Hardware?**
Hardware

**Comment by MrCsabaToth** [comment]
It was said to be a multi year project, so the start date should be before 2022, sometimes 2021 or 2020

**Comment by MrCsabaToth** [comment]
> It was said to be a multi year project, so the start date should be before 2022, sometimes 2021 or 2020

Maybe it was a multi year in-house but not from the official release
