### ISSUE TITLE
Search by Image on Google Images

### ISSUE THREAD

**Issue by smileyhead** [codyogden/killedbygoogle#1409]
**What's the Product's Name?**
Search by Image on Google Images.
**Describe the product in a single sentence.**
A feature on Google Images that lets you reverse search an image.
**When was the product launched? Provide a specific date, if possible.**
June 2011
**When was the product discontinued? Provide a specific date, if possible.**
Sometime 2022
**What type of product was it? App, Service, or Hardware?**
Service

You used to be able to search by image on Google Images, which has now been replaced by Google Lens. While the latter does have an interface for finding the image source, it is vastly simplified compared to the former, only providing a list view of results and no filters, sorting by resolution, or gallery view like on Google Images. From what I can see, there is no way of accessing the classic Image Search feature on Google Images, as even its button on the front page has been replaced by a Lens button. Attempting to search directly through the URL (`http://www.google.com/searchbyimage?image_url=`) just redirects you to the Google Images front page.

**Comment by FaviFake** [comment]
It doesn't feel like it should count as a defunct service, it's more like a redesign that added some features and removed some. It removed gallery view and filters, sure, but it also made the experience much more user-friendly and simple to use. I don't think it should be added to the graveyard.

**Comment by smileyhead** [comment]
I see your argument, however Lens is very different to Image Search. Yes, they both work with images, but Lens is used to search for content _within_ an image, while Image Search is used to search the web for the image _itself_. The Image Search built into Lens is a secondary purpose and very much dumbed-down compared to classic Image Search.

**Comment by FaviFake** [comment]
> Lens is very different to Image Search

It's not really that different. Do you really prefer Google having two slightly different parallel products instead of just one?

> The Image Search built into Lens is [...] very much dumbed-down compared to classic Image 

I disagree. As i said, it removed gallery view and filters, sure, but it also made the experience much more user-friendly and simpler to use. It's really just a UI and name change.

**Comment by smileyhead** [comment]
Like I said,
> Lens is used to search for content within an image, while Image Search is used to search the web for the image itself. 
They serve completely different purposes.

**Comment by FaviFake** [comment]
We disagree :)
