### ISSUE TITLE
Mobile-Friendly Test tool, Mobile-Friendly Test API, and Mobile Usability report shutting down December 1, 2023

### ISSUE THREAD

**Issue by catharsis71** [codyogden/killedbygoogle#1421]
**What's the Product's Name?**

Mobile-Friendly Test tool, Mobile-Friendly Test API, and Mobile Usability report

**Describe the product in a single sentence.**

Tools for testing mobile-friendliness of websites

**When was the product launched? Provide a specific date, if possible.**

2014 / 2016 https://searchengineland.com/google-launches-new-mobile-friendly-testing-tool-249734

**When was the product discontinued? Provide a specific date, if possible.**

December 1, 2023 https://developers.google.com/search/blog/2023/04/page-experience-in-search

**What type of product was it? App, Service, or Hardware?**

API and web tool

**Comment by fenopa** [comment]
bump
