### ISSUE TITLE
Pixel Pass 2021-2023

### ISSUE THREAD

**Issue by slashtab** [codyogden/killedbygoogle#1426]
**What's the Product's Name?**
Pixel Pass

**Describe the product in a single sentence.**
A way to help users save money by bundling Pixel phones with Google services.

**When was the product launched? Provide a specific date, if possible.**
2021

**When was the product discontinued? Provide a specific date, if possible.**
August 29, 2023

**What type of product was it? App, Service, or Hardware?**
Service and Hardware

**Comment by egemen404** [comment]
Launched with Pixel 6/6Pro, on Oct 28,2021. https://en.wikipedia.org/wiki/Pixel_6#cite_note-PixelPass-56
