### ISSUE TITLE
Play Movies and TV was not killed 2 years ago

### ISSUE THREAD

**Issue by ivoros** [codyogden/killedbygoogle#1428]
The site states:

![image](https://github.com/codyogden/killedbygoogle/assets/46140014/84d4388d-628e-42ce-b59e-a4367a034f1a)

But that app is still very much alive on my Android 13 phone AND on my Android TV 10 as of today and Google is planning to kill it in October **_this_** year.

See: https://arstechnica.com/gadgets/2023/09/google-is-killing-play-movies-tv-will-only-have-three-video-stores-left/?comments=1&comments-page=1

I know there were a lot of renaming and iterations, but an app that is called Google Play Movies and TV is alive and installable as of today.

**Comment by slashtab** [comment]
Right!! further to add to it... It was killed partially in 2021. [Read here](https://arstechnica.com/gadgets/2021/04/google-is-killing-google-play-movies-tv-on-smart-tvs/)

>Google is killing “Google Play Movies & TV” on smart TVs

I think it was misunderstood.
