### ISSUE TITLE
App: Live Channels

### ISSUE THREAD

**Issue by the4anoni** [codyogden/killedbygoogle#1429]
**What's the Product's Name?**

Live Channels

**Describe the product in a single sentence.**

App for watching TV

**When was the product launched? Provide a specific date, if possible.**
10.12.2014
**When was the product discontinued? Provide a specific date, if possible.**
31.07.2023
**What type of product was it? App, Service, or Hardware?**

App

**Comment by SamLeatherdale** [comment]
Can this be reopened? I think Live Channels should be included on the site.
