### ISSUE TITLE
Add Google Jamboard App

### ISSUE THREAD

**Issue by mwarkentin** [codyogden/killedbygoogle#1435]
**What's the Product's Name?**

Jamboard App

**Describe the product in a single sentence.**

Collaborative white boarding software.

**When was the product launched? Provide a specific date, if possible.**

**When was the product discontinued? Provide a specific date, if possible.**

October 1st, 2024

https://www.theverge.com/2023/9/28/23894509/google-jamboard-whiteboarding-app-graveyard

**What type of product was it? App, Service, or Hardware?**

App

**Comment by junesix** [comment]
Jamboard hardware is also dead https://support.google.com/a/answer/7374455
