### ISSUE TITLE
Tensorboard.dev

### ISSUE THREAD

**Issue by samxu29** [codyogden/killedbygoogle#1447]
**What's the Product's Name?**
Tensorboard.dev

**Describe the product in a single sentence.**
https://tensorboard.dev/
https://blog.tensorflow.org/2019/12/introducing-tensorboarddev-new-way-to.html
A managed service that enables you to easily host, track, and share your ML experiments for free.

**When was the product launched? Provide a specific date, if possible.**
December 02, 2019

**When was the product discontinued? Provide a specific date, if possible.**
December 31, 2023

**What type of product was it? App, Service, or Hardware?**
Service

**Comment by ArceusDev** [comment]
I have opened a pull request on tensorboard.dev and followed all the steps. Hoping to get this pull request merged. Thank you
