### ISSUE TITLE
Shopping list and assistant notes

### ISSUE THREAD

**Issue by rothgar** [codyogden/killedbygoogle#1464]
**What's the Product's Name?**
Shopping list
Assistant notes

**Describe the product in a single sentence.**
Notes dictated to Google assistant were part of the assistant app and when you would say "Add ____ to my shopping list" it would go to a special list at shoppinglist.google.com

Both will migrated to keep.google.com

**When was the product launched? Provide a specific date, if possible.**
I'm not sure.

**When was the product discontinued? Provide a specific date, if possible.**
I don't know when they started migrating data but the last day to export data is May 1, 2024

https://support.google.com/assistant/answer/14171370?hl=en

**What type of product was it? App, Service, or Hardware?**
Assistant notes was a feature of the assistant app and the shopping list was a standalone service

**Comment by agalonsk** [comment]
I came here to post this. It finally happened and they pushed my shopping list into Keep (to much annoyance of my family)

**Comment by rothgar** [comment]
Looks like I got moved today too :(
