### ISSUE TITLE
Google TV (kind-of)

### ISSUE THREAD

**Issue by ThePlayer14** [codyogden/killedbygoogle#1470]
**What's the Product's Name?**
Google TV
**Describe the product in a single sentence.**
Google TV was the service that replaced Google Play Movies & TV, which was merged into Google TV.
**When was the product launched? Provide a specific date, if possible.**
September 2020
**When was the product discontinued? Provide a specific date, if possible.**
January 17, 2024
**What type of product was it? App, Service, or Hardware?**
Service
**References:**
* https://support.google.com/androidtv/thread/247411854/upcoming-changes-to-google-play-movies-tv
* https://arstechnica.com/gadgets/2023/12/google-play-movies-gets-a-new-shutdown-date-january-17/

**Comment by Frisk9571** [comment]
Uhh... where does it exactly say that Google TV is being shut down? All it says is that Google Play Movies and TV is getting shut down on Android TV... The Google TV app on regular Android will live on.
Note: After reading the official Google helpdesk link on the matter before posting this comment, I see now that this _could_ be misinterpreted as "Google TV as a whole is shutting down" so...
