### ISSUE TITLE
Remove Fortune from website

### ISSUE THREAD

**Issue by WebSnke** [codyogden/killedbygoogle#1474]
The link to the Fortune article in the "as seen on" section seems to have been removed and now redirects to the homepage instead.

**Comment by codyogden** [comment]
This might be a geo issue. Link is working as expected.

<img width="1191" alt="Screenshot 2024-01-02 at 7 16 56 AM" src="https://github.com/codyogden/killedbygoogle/assets/11383626/ba360f29-8859-4a0a-910c-4871d7ec1f18">

**Comment by WebSnke** [comment]
> This might be a geo issue. Link is working as expected.
> <img alt="Screenshot 2024-01-02 at 7 16 56 AM" width="1191" src="https://private-user-images.githubusercontent.com/11383626/293722981-ba360f29-8859-4a0a-910c-4871d7ec1f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTIzNTAsIm5iZiI6MTcwNDIxMjA1MCwicGF0aCI6Ii8xMTM4MzYyNi8yOTM3MjI5ODEtYmEzNjBmMjktODg1OS00YTBhLTkxMGMtNDg3MWQ3ZWMxZjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmOTY2ZDFiMjY0MjI2N2ZkZWQ1YjEzODAyZDAwNDNhMmZjYzA1YWY3NTRkZTNkZDQwZmRjYzI5MTZjYzQwNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8335R0hhG4daOqSVNffSbeNhHyq85nbzA4htFEtoQDo">

Ok, thanks. Could you maybe also take a look at my other pull requests?
