### ISSUE TITLE
Add Google Search Cached Pages?

### ISSUE THREAD

**Issue by Cobertos** [codyogden/killedbygoogle#1480]
Ars Technica has [an article](https://arstechnica.com/gadgets/2024/02/google-search-kills-off-cached-webpages/) about it, also confirmed by the search liaison Twitter account. 

Not sure if this qualifies as it's only a feature, but it was a large and useful one.

**What's the Product's Name?**

Google Search Cached Pages

**Describe the product in a single sentence.**

Google Search Cached Pages allowed users to view archived versions of webpages stored by Google Search.

**When was the product launched? Provide a specific date, if possible.**

The earliest I could confirm was as early as Dec 2000 from [this archived search page which shows Cached links directly in search results](https://web.archive.org/web/20001204221900/google.com/search?q=test)

Im not sure I can confirm any earlier date than Dec 2000. I can't find any images of search results before this date and didn't look harder on archive.org.

Google search started in 1995? So sometimes between then and 2000.

**When was the product discontinued? Provide a specific date, if possible.**

No date except "near future" after Feb 2024. The cached link from the sidebar was removed, and the `cache:` has yet to be removed but is confirmed to be removed in the future.

**What type of product was it? App, Service, or Hardware?**

Service or App. It's more of a feature

**Comment by arnesetzer** [comment]
See #1481 
As far as I'm concerned the oldest mention is in [Feburary 2000](https://twitter.com/searchliaison/status/1744755094271455434)

**Comment by Cr4zyc4k3** [comment]
Not complete

**Comment by arnesetzer** [comment]
Still active
