### ISSUE TITLE
Bard

### ISSUE THREAD

**Issue by rereradu** [codyogden/killedbygoogle#1483]
What's the Product's Name?
**Bard**

Describe the product in a single sentence.
**Chat Based AI Tool from Google**

When was the product launched? Provide a specific date, if possible.
**March 21, 2023**

When was the product discontinued? Provide a specific date, if possible.
**February 8, 2024**

What type of product was it? App, Service, or Hardware?
**App / Service**

**Comment by petrk94** [comment]
Source? I still can use it

**Comment by mollthecoder** [comment]
I would call it a rebranding.

**Comment by JJRcop** [comment]
It is absolutely a rebranding and not a killed product, see [here](
https://blog.google/products/gemini/bard-gemini-advanced-app/).

Trying to call this another "killed" product only harms the journalistic integrity of the website by artificially inflating the number of killed products, even though this one is still active, usable, and not dying any time soon, only bearing a new name.

There is not only no need for this but as I have described, this will harm the website by making it look like one of those tabloid magazines that exaggerate the facts.

**Comment by rhythmichi** [comment]
Does https://experiments.withgoogle.com/ have the same situation? It was replaced by Labs,but it's still up. Though you cant add anything to it anymore.
