### ISSUE TITLE
Google Groups USENET support

### ISSUE THREAD

**Issue by sinni800** [codyogden/killedbygoogle#1486]
**What's the Product's Name?**
Google Groups, USENET support
**Describe the product in a single sentence.**
Provides discussion groups like a forum and connects to a worldwide service called "usenet". Only the usenet support is being canceled, which means groups local to Google Groups can still continue to exist and communicate. 
**When was the product launched? Provide a specific date, if possible.**
February 2001
**When was the product discontinued? Provide a specific date, if possible.**
22 February 2024
**What type of product was it? App, Service, or Hardware?**
Service

Source: https://support.google.com/groups/answer/11036538?visit_id=638436911607522641-3279146927&p=usenet&rd=1

**Comment by mollthecoder** [comment]
No way, usenet was supported for this long?
