### ISSUE TITLE
Google Pay

### ISSUE THREAD

**Issue by ZLima12** [codyogden/killedbygoogle#1488]
**What's the Product's Name?**
Google Pay
**Describe the product in a single sentence.**
The app allowed users to store, send, and receive money to/from other users.
**When was the product launched? Provide a specific date, if possible.**
November 18, 2020
**When was the product discontinued? Provide a specific date, if possible.**
June 4, 2024
**What type of product was it? App, Service, or Hardware?**
App

**Comment by DesiOtaku** [comment]
In case a link is required: https://www.androidpolice.com/google-pay-shutting-down-b/

**Comment by dexterous** [comment]
Sometimes added a PR #1489

**Comment by arnav-kr** [comment]
One thing to notice there is its county specific, it hasn't been discontinued in countries say India https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.paisa.user

that makes me wonder how country specific kills are handled?

**Comment by RageGamerBoi** [comment]
Google Pay dies today.
Maybe it could say “Google Pay US” or something?
