### ISSUE TITLE
Keen

### ISSUE THREAD

**Issue by georgemoodier** [codyogden/killedbygoogle#1498]
**What's the Product's Name?**
Keen
**Describe the product in a single sentence.**
Pinterest-like social media platform
**When was the product launched? Provide a specific date, if possible.**
June 18, 2020
**When was the product discontinued? Provide a specific date, if possible.**
March 24, 2024
**What type of product was it? App, Service, or Hardware?**
Service

**Comment by jeremyredhead** [comment]
Dunno if a link to "cite" is wanted or needed but this is the one where I found out about it: 
https://chipp.in/news/google-is-shutting-down-keen-a-platform-you-may-have-never-heard-of/
(blog apparently edited/written by Martin Brinkmann of Ghacks)
