### ISSUE TITLE
Firebase Dynamic Links

### ISSUE THREAD

**Issue by Shady-Selim** [codyogden/killedbygoogle#1519]
**Firebase Dynamic Links**

**With Dynamic Links, your users get the best available experience for the platform they open your link on. If a user opens a Dynamic Link on iOS or Android, they can be taken directly to the linked content in your native app. If a user opens the same Dynamic Link in a desktop browser, they can be taken to the equivalent content on your website.**

**May 17, 2017**

**August 25, 2025**

**Service**

**Comment by k3a** [comment]
I was not using it myself but since it was a service to host links, I can imagine it will cause a lot of pain for people as those links will stop working. Another reminder to avoid relying on Google and self-host such things. https://firebase.google.com/support/dynamic-links-faq

**Comment by Shady-Selim** [comment]
> I was not using it myself but since it was a service to host links, I can imagine it will cause a lot of pain for people as those links will stop working. Another reminder to avoid relying on Google and self-host such things. https://firebase.google.com/support/dynamic-links-faq

Yes my company was deeply affected, and we started working on our in-house replacement for not facing the same problem again in the future

Another reason for not fully relay on Google services for mobile, is that publishing apps on Huawei stores would require a lot of refactor
