### ISSUE TITLE
Location History

### ISSUE THREAD

**Issue by TomGoBravo** [codyogden/killedbygoogle#1520]
**What's the Product's Name?**
`Location History`, now called `Timeline for Web Maps`

**Describe the product in a single sentence.**
Location History is a Google Account setting that creates Timeline, a personal map that helps you remember places you go, routes and trips you've taken. (https://support.google.com/accounts/answer/3118687?hl=en)

It will be no longer accessible outside of the Google Maps app on a mobile phone.

**When was the product launched? Provide a specific date, if possible.**
Nov 10, 2009
https://googlemobile.blogspot.com/2009/11/google-latitude-now-with-location.html

**When was the product discontinued? Provide a specific date, if possible.**
Gradually being turned down starting Dec 2023
https://blog.google/products/maps/updates-to-location-history-and-new-controls-coming-soon-to-maps/

**What type of product was it? App, Service, or Hardware?**
Service

**Comment by forresthopkinsa** [comment]
Agreed, this is a significant headstone in the graveyard. Location History was a cloud tool that synced all your devices to build a pretty comprehensive and browseable history of where you've been over the years. It's an invaluable tool and its replacement is a sad replica. There is no cross-device sync anymore and all of the tooling in the desktop app will be inaccessible. The back-end feature on Google servers is being killed completely; the new "Timeline" is just an in-app database that exists only on-device.
