### ISSUE TITLE
Google Business Messaging

### ISSUE THREAD

**Issue by ltetreault-va** [codyogden/killedbygoogle#1522]
**What's the Product's Name?**
[Google Business Messages](https://businessmessages.google/)

**Describe the product in a single sentence.**
An API that allowed businesses to have a custom chat agent that customers could contact through their business listing in Google Search/Maps

**When was the product launched? Provide a specific date, if possible.**
[December 3, 2019](https://developers.google.com/business-communications/business-messages/resources/release-notes?hl=en)

**When was the product discontinued? Provide a specific date, if possible.**
July 31st, 2024

**What type of product was it? App, Service, or Hardware?**
Service

**Additional Links**
https://developers.google.com/business-communications/business-messages/resources/release-notes/update-on-gbm?hl=en

**Comment by toineenzo** [comment]
Duplicate of https://github.com/codyogden/killedbygoogle/issues/1521
