### ISSUE TITLE
Google My Business Profile Chat Removed

### ISSUE THREAD

**Issue by alexander-zierhut** [codyogden/killedbygoogle#1524]
**What's the Product's Name?**
Google My Business Profile Chat

**Describe the product in a single sentence.**
Customers were able to open a chat from the businesses profile, i.e. Google Maps and Google Search.

**When was the product launched? Provide a specific date, if possible.**
I wasn't able to find out. That's why I am opening an issue instead of a PR.

**When was the product discontinued? Provide a specific date, if possible.**
- Starting July 15, customers will no longer be able to start new chat conversations with your business through Google. Customers who are currently in chat conversations with your business will be notified that chat will be disabled.
- On July 31, chat will be disabled, meaning you will no longer receive new chat messages after that.

**What type of product was it? App, Service, or Hardware?**
Service

**Original Notification (in German)**
Wir möchten Ihnen mitteilen, dass wir die Chatfunktion in Google Unternehmensprofil am 31. Juli 2024 einstellen. Uns ist bewusst, dass das möglicherweise etwas überraschend für Sie kommt – doch wir arbeiten kontinuierlich an der Verbesserung unserer Produkte und müssen manchmal schwierige Entscheidungen treffen, die sich auf die Unternehmen und Partner auswirken, mit denen wir zusammenarbeiten. Google möchte selbstverständlich ein verlässlicher Partner für Sie bleiben und Sie weiterhin bei der Verwaltung Ihres Unternehmens unterstützen.

Ab 15. Juli werden keine neuen Unterhaltungen mehr erstellt. Am 31. Juli läuft die Chatfunktion dann vollständig aus. Hinweis: Kundinnen und Kunden haben weiterhin die Möglichkeit, Ihr Unternehmen über die Google Suche und auf Google Maps zu finden und zu kontaktieren. Sie erhalten außerdem weitere Informationen über Links zu Ihrer Website, die Unternehmensbeschreibung, Fotos und sonstige Auskünfte, die Sie in Ihrem Unternehmensprofil teilen.

Wenn Sie weitere Fragen zu dieser Änderung haben, finden Sie hier [weitere Informationen](REMOVED LINK) dazu. Wir möchten, dass Ihr Unternehmensprofil für Sie weiterhin ein hilfreiches Tool zur Verwaltung Ihres Unternehmens bleibt.

**Comment by goatandsheep** [comment]
link also here https://developers.google.com/business-communications/business-messages/resources/release-notes/update-on-gbm

**Comment by goatandsheep** [comment]
apparently it was launched in 2017 https://www.linkedin.com/pulse/google-streamlines-business-chat-fully-transitions-messaging-govil-ktrhf#:~:text=The%20Origins%20of%20Business%20Chat,without%20ever%20leaving%20Google's%20apps.
