### ISSUE TITLE
material-components/material-web

### ISSUE THREAD

**Issue by jogibear9988** [codyogden/killedbygoogle#1532]
**What's the Product's Name?**
material-components/material-web

**Describe the product in a single sentence.**
Webcomponents with Material Design

**When was the product launched? Provide a specific date, if possible.**
27.03.2018
first commit: https://github.com/material-components/material-web/commit/dd0edf200b8c6716b8e25c3e245cd828fc8988c1

**When was the product discontinued? Provide a specific date, if possible.**
6.2024 -> see https://github.com/material-components/material-web/discussions/5642

**What type of product was it? App, Service, or Hardware?**
webcomponent library

**Comment by ma499** [comment]
Premature as the project continues to be actively maintained - just feature development is an undefined hiatus.
