### ISSUE TITLE
The Recent (possible) Death of Google Video Quality Report

### ISSUE THREAD

**Issue by DrEngineer1** [codyogden/killedbygoogle#1538]
**What's the Product's Name?**
Google Video Quality Report
**Describe the product in a single sentence.**
A diagnostic tool to measure the quality of YouTube videos through your network ISP and the time of day in a graph.
**When was the product launched? Provide a specific date, if possible.**
January 22, 2014
**When was the product discontinued? Provide a specific date, if possible.**
July 2, 2024
**What type of product was it? App, Service, or Hardware?**
Service

**Comment by qtlunya** [comment]
#1537

**Comment by ra-zy** [comment]
![Screenshot 2024-07-17 at 9 18 23 PM](https://github.com/user-attachments/assets/2855f1dc-2851-43bd-9ea6-98cee3eb71a1)
Here's a screenshot of the page today
