### ISSUE TITLE
Add the redirect part of goo.gl

### ISSUE THREAD

**Issue by sevenc-nanashi** [codyogden/killedbygoogle#1540]
I think it should be noted that goo.gl stopped redirecting (not only its registration).

---

**What's the Product's Name?**

Google URL shortener, the redirect part.

**Describe the product in a single sentence.**

(I can't explain the context in a single sentence)

**When was the product launched? Provide a specific date, if possible.**

2019-03-30 (when the shortener stopped generating new URLs)

**When was the product discontinued? Provide a specific date, if possible.**

[2025/8/25](https://developers.googleblog.com/en/google-url-shortener-links-will-no-longer-be-available/)

**What type of product was it? App, Service, or Hardware?**

Service.

**Comment by Yankue** [comment]
Since we are now past 23rd August 2024, Google is now displaying warning messages whenever you visit a URL that uses this service. It is still a year until they are going to officially break it though.

https://developers.googleblog.com/en/google-url-shortener-links-will-no-longer-be-available/
