### ISSUE TITLE
Add Chrome manifest v2 extensions

### ISSUE THREAD

**Issue by safinaskar** [codyogden/killedbygoogle#1543]
**What's the Product's Name?**
Google Chrome's manifest v2 extensions

**Describe the product in a single sentence.**
Old flavor of Chrome's extensions

**When was the product launched? Provide a specific date, if possible.**
Don't know

**When was the product discontinued? Provide a specific date, if possible.**
Starting June 2024, v2 manifest extensions will be gradually disabled

https://blog.chromium.org/2024/05/manifest-v2-phase-out-begins.html
https://developer.chrome.com/blog/resuming-the-transition-to-mv3

**What type of product was it? App, Service, or Hardware?**
Service (Chrome Apps are listed as service, so let's list v2 extensions as service, too)

Killing of v2 extensions created a big controvercy. v2 extensions had features useful for adblockers. New manifest version (v3) is less capable in this field. Author of uBlock Origin wrote a big critique of v3 manifest: https://issues.chromium.org/issues/40598795#comment24 . Other critique:

https://www.theregister.com/2022/09/08/ad_blockers_chrome_manifest_v3/
https://www.eff.org/deeplinks/2021/12/googles-manifest-v3-still-hurts-privacy-security-innovation
https://www.eff.org/deeplinks/2021/12/chrome-users-beware-manifest-v3-deceitful-and-threatening

Many products at "Killed by Google" are products killed because they are not really useful. Manifest v2 extensions seem to be opposite: it seems they are being killed exactly because they are useful! Manifest v2 extensions allow very advanced ad blocking, and Google doesn't like this!

**Comment by driedpampas** [comment]
related to #1292

**Comment by safinaskar** [comment]
https://github.com/codyogden/killedbygoogle/issues/1292 was closed by Github stale bot. This is absurd. See "GitHub stale bot considered harmful" ( https://drewdevault.com/2021/10/26/stalebot.html )

**Comment by safinaskar** [comment]
[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
