### ISSUE TITLE
Add Google Reader

### ISSUE THREAD

**Issue by MaxGripe** [codyogden/killedbygoogle#1569]
**What's the Product's Name?**
Google Reader.

**Describe the product in a single sentence.**
RSS feed aggregator.

**When was the product launched? Provide a specific date, if possible.**
October 7, 2005.

**When was the product discontinued? Provide a specific date, if possible.**
July 1, 2013.

**What type of product was it? App, Service, or Hardware?**
App.

**Comment by infeeeee** [comment]
Already there: https://github.com/codyogden/killedbygoogle/blob/0fc85ec5e968951d70c3cd4c3d6db35fd3991f50/graveyard.json#L618
