### ISSUE TITLE
Chrome Frame

### ISSUE THREAD

**Issue by thomasbilk** [codyogden/killedbygoogle#199]
**What's the Product's Name?**
Google Chrome Frame

* https://en.wikipedia.org/wiki/Google_Chrome_Frame 
* https://www.chromium.org/developers/how-tos/chrome-frame-getting-started
* https://blog.chromium.org/2013/06/retiring-chrome-frame.html

**Any idea when it was killed by Google?**
It was not really needed any more.

**Comment by codyogden** [comment]
Thank you for your detailed research!
