### ISSUE TITLE
App vs. Service vs. Product

### ISSUE THREAD

**Issue by Lonami** [codyogden/killedbygoogle#201]
Enhancement idea. I think it could be interesting to have other visual means to differentiate between applications, services or products Google has killed. The page could also support filtering by type, and show the total number so users could make an idea. E.g.
<pre>
<b>all (76)</b> - apps (40) - services (20) - products (16)
</pre>

**Comment by codyogden** [comment]
I love this idea! My only suggestion is to change `products` to `hardware` or `devices` since everything listed is a product.

JSON schema for `graveyard.json` needs a small update, and the test would need to verify the type meets one of the three type options:

```
  {
    "dateClose": "YYYY-MM-DD",
    "dateOpen": "YYYY-MM-DD",
    "description": "[Product Name] was a single sentence overview of the product or service.",
    "link": "https://any.link-to-a.source/will/work-and-wikipedia-is-cool",
    "name": "[Product Name]",
    "type": "app|device|service"
  }
```

**Comment by codyogden** [comment]
WIP in #233.
