### ISSUE TITLE
Google AdWords

### ISSUE THREAD

**Issue by sgammon** [codyogden/killedbygoogle#204]
**What's the Product's Name?**
Google AdWords

**Any idea when it was killed by Google?**
2018. It has been rebranded and combined with other products to create Google Ads.

**Comment by sgammon** [comment]
some background (also pasted in #205): https://searchengineland.com/google-is-retiring-the-adwords-doubleclick-brands-in-a-major-rebranding-aimed-at-simplification-301073

**Comment by kayvonkamyar** [comment]
It was just renamed!

**Comment by sgammon** [comment]
AdWords is reconstructed as a new unified platform, isn't it? or is adwords still a product, just renamed? @kayvonkamyar

**Comment by grant** [comment]
Just renamed.
https://en.wikipedia.org/wiki/Google_Ads

**Comment by codyogden** [comment]
Since it's still alive, we'll keep this one above ground...for now.
