### ISSUE TITLE
Google Chrome Apps

### ISSUE THREAD

**Issue by benwinding** [codyogden/killedbygoogle#21]
**Date Closed/Discontinued**

2018

**Date Opened/Launched**

2013

**Description**
https://en.wikipedia.org/wiki/Google_Chrome_App

**Link**

https://en.wikipedia.org/wiki/Google_Chrome_App

**Comment by codyogden** [comment]
This is a good one. Thanks!!

**Comment by limeb** [comment]
The link was input wrong.  It links to Google Desktop.

**Comment by limeb** [comment]
https://github.com/codyogden/killedbygoogle/pull/210
