### ISSUE TITLE
Google Hangouts

### ISSUE THREAD

**Issue by codyogden** [codyogden/killedbygoogle#217]
Google will be shutting down Hangouts in 2020. Date pending.

https://9to5google.com/2018/11/30/google-hangouts-shutting-down/

**Comment by cTxplorer** [comment]
No, Hangouts is not shutting down. Ratuer it would be upgraded to Hangouts Chat and Hangouts Meet. 

I'm not sure whether separating a product into two different entities is considered as shutdown here. 

https://www.androidcentral.com/google-hangouts-reportedly-shutting-down-2020

**Comment by limeb** [comment]
@cTxplorer true but the new versions are supposed to be commercial/business only.

That hardly helps consumers like us.

**Comment by lbenedetto** [comment]
New info points to October 2019

https://arstechnica.com/gadgets/2019/01/the-great-google-hangouts-shutdown-begins-october-2019/

**Comment by codyogden** [comment]
I'm cool if someone wants to PR.

```json
  {
    "dateClose": "2019-10-31",
    "dateOpen": "2013-03-15",
    "description": "Google Hangouts was a communication platform which included messages, video chat, and VOIP features. Execution date is tentative.",
    "link": "https://arstechnica.com/gadgets/2019/01/the-great-google-hangouts-shutdown-begins-october-2019/",
    "name": "Google Hangouts",
    "type": "service"
  }
```
