### ISSUE TITLE
Combine Nexus Phone Devices

### ISSUE THREAD

**Issue by dJani97** [codyogden/killedbygoogle#221]
Listing services and great ideas killed by Google is a nice idea.
But listing actual hardware (even the ones that got continued!!!) makes the site unnecessarily overcrowded.

Listing the Nexus series? Why not? It's a sad story, I miss it too.
Listing Pixel? For what reason? It still has successors, and is a very successful line of phones.

I think you should consider listing hardware based on their product line, the general idea that they stood for. Going along with the above example: Nexus is dead, Pixel is not.

**Comment by codyogden** [comment]
I feel combining the Nexus phones into one entry is a good move. But there are some Nexus devices that are **not** phones and don't have a clear successor (Nexus Q & Nexus Player).

I agree that Pixel device(s) aren't really needed on the list either (it was probably added during Hacktoberfest).

Anyone is welcome to do some clean up and editing if they'd like to contribute. 😄
