### ISSUE TITLE
Missing: Google Health

### ISSUE THREAD

**Issue by brianleemcqueen** [codyogden/killedbygoogle#222]
Google Health was a personal health information centralization service (sometimes known as personal health record services) by Google introduced in 2008 and discontinued in 2011.[1] The service allowed Google users to volunteer their health records – either manually or by logging into their accounts at partnered health services providers – into the Google Health system, thereby merging potentially separate health records into one centralized Google Health profile.

[https://en.wikipedia.org/wiki/Google_Health](https://en.wikipedia.org/wiki/Google_Health)

**Comment by codyogden** [comment]
This one is already on the list. Thank you!
