### ISSUE TITLE
Youtube Video Editor

### ISSUE THREAD

**Issue by codyogden** [codyogden/killedbygoogle#224]
Daniel, on Twitter, mentioned YouTube video editor (2010-2017).

https://twitter.com/dno1967b/status/1070022092303806464

We'll need to find some dates and a good sentence for this one.

**Comment by Trojan7z7VZX** [comment]
An ancient (It was **so** old) project that was a part of YouTube for ages, people used it to merge clips, stabilize their videos and controlling the brightness and volume. You could also upload some pictures and use the Photo Slideshow feature it had but on September 20th, 2017, the project was **killed by Google!!!!** (damn it I can't edit my vids anymore) Anyways, here's [a useful video ](https://www.youtube.com/watch?v=PdMUNHfbvhU)I found.

**Comment by codyogden** [comment]
Research dump. A couple editors iterations were actually around...

YouTube Remixer (2007-2010) - http://archive.today/nhJmT

YouTube Editor (2010-2017) - http://googlesystem.blogspot.com/2010/06/youtube-video-editor.html

**Comment by codyogden** [comment]
Resolved #344
