### ISSUE TITLE
Google Allo

### ISSUE THREAD

**Issue by Knifa** [codyogden/killedbygoogle#225]
**Google Allo**

https://9to5google.com/2018/12/05/google-allo-shutting-down/

Absolutely lmao. No official date yet but I guess it's coming.

**Comment by codyogden** [comment]
We marked it as dead this past January, but we'll dig it up and strap it to a guillotine when Google releases an official date.

**Comment by Be1con** [comment]
[Google Confirmed this new](https://www.blog.google/products/messages/latest-messages-allo-duo-and-hangouts/)
