### ISSUE TITLE
Add Category Filters

### ISSUE THREAD

**Issue by joaodforce** [codyogden/killedbygoogle#228]
Bellow the Search field there should be a category filter bar or something.

That would let us pick what kind of services Google has killed, like
"Messaging Services" -> Hangouts, Allo, Android SMS, etc...
"Social networks" -> Orkut, Google+, etc...
That way were can easily visualize how incompetent they had been in creating some kind of service.

This way also giving categories to all dead services.

**Comment by codyogden** [comment]
I like this idea. In #201 we were talking about more broad buckets like `app` (web & mobile), `device` (hardware), and `service` (APIs) and adding similar functionality to apply those filters.

I'd to keep choice overload at a minimum, and decrease any opportunity for accessibility to be hindered.

Thoughts?

**Comment by joaodforce** [comment]
Maybe adding a Radio group designed as Segmented control buttons 

Something like this, that would fit the design of the page of course. My only concern is that it could become very convoluted once too. 
Many categories appear.

Maybe keeping the categories under 4 big umbrelas and opting for a fifth "Others" category.
![uisegmentedcontrol_button_ios7](https://user-images.githubusercontent.com/9410916/49594061-2ea9fd80-f95c-11e8-8fde-beea455327e7.jpg)

And then for more refined filters there could be a small button next to it in order to select advanced filters.
