### ISSUE TITLE
Missing item: Nexus 10

### ISSUE THREAD

**Issue by helgrind** [codyogden/killedbygoogle#230]
**What's the Product's Name?**
Nexus 10

**Any idea when it was killed by Google?**
2014 from the Play Store by the looks of it:
https://www.androidheadlines.com/2014/10/nexus-7-nexus-10-longer-sold-play-store.html

Although I'm pretty sure it's half of the new home hub...

**Comment by codyogden** [comment]
Per #221, looks like we'll end up combining "Nexus" as a killed brand/line for phones and tablets.
