### ISSUE TITLE
Fusion Tables

### ISSUE THREAD

**Issue by jmorrison1847** [codyogden/killedbygoogle#237]
**What's the Product's Name?**
[Google Fusion Tables](https://support.google.com/fusiontables/answer/2571232)

**Any idea when it was killed by Google?**
On December 11, 2018 the Google Fusion Tables team announced it would be "turning down" the service on December 3, 2019 after almost nine years. From the announcement:

>For a long time, it was one of the few free tools for easily visualizing large datasets, especially on a map. Since then, Google has developed several alternatives, providing deeper experiences in more specialized domains.

I would make a PR, but I'm too scared to mess something up. This was a small project relative to other Google initiatives, but has a loyal following that will undoubtedly be sad. RIP, Fusion Tables.

**Comment by codyogden** [comment]
#236 got you by a couple minutes. :) Thanks for letting us know!

**Comment by jmorrison1847** [comment]
oh dang, you good!
