### ISSUE TITLE
Google Nearby

### ISSUE THREAD

**Issue by Immolated** [codyogden/killedbygoogle#246]
Google Nearby,
a service that enabled recieving contextual messages from bluetooth beacons without any specific app installed.

Introduced in Q1/Q2 of 2016,

killed in December 6th 2018.

Link to a blog post for reference: [https://android-developers.googleblog.com/2018/10/discontinuing-support-for-android.html](url)

It was a service.

**Comment by NotARossFan** [comment]
Submitted via PR #334 
https://github.com/codyogden/killedbygoogle/pull/334

**Comment by codyogden** [comment]
Resolved in #334
