### ISSUE TITLE
Addition: YouTube Annotations

### ISSUE THREAD

**Issue by DiamondDude** [codyogden/killedbygoogle#250]
**What's the Product's Name?**
YouTube Annotations
**Describe the product in a single sentence.**
It allow users to add text, link to other videos, and spotlight your videos.
**When was the product launched? Provide a specific date, if possible.**
2008
**When was the product discontinued? Provide a specific date, if possible.**
January 15th, 2019
**What type of product was it? App, Service, or Hardware?**
Service

**Comment by codyogden** [comment]
Resolved in #329
