### ISSUE TITLE
Feature Request: Add icon or logo of product/service

### ISSUE THREAD

**Issue by styfle** [codyogden/killedbygoogle#252]
Right now, the page uses the same icon for the type of thing that was killed.

Could you instead display the logo or an image of the product that was discontinued?

**Comment by codyogden** [comment]
I didn't want to use logos as many of them ended up being some form of the Google logo with additional word mark (example below). I like the idea of screenshots as an alternative to the logos, and they should be pretty easy to source for most of the apps/services.

![Google Friend Connect Logo](https://www.track5media.com/wp-content/uploads/2016/05/friend-connect-logo-415x266.png)

**Comment by asfo** [comment]
> I didn't want to use logos as many of them ended up being some form of the Google logo with additional word mark (example below). I like the idea of screenshots as an alternative to the logos, and they should be pretty easy to source for most of the apps/services.
> 
> ![Google Friend Connect Logo](https://camo.githubusercontent.com/ffc708ed7839c94c2bc900e84f5d7b656ec521c3/68747470733a2f2f7777772e747261636b356d656469612e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031362f30352f667269656e642d636f6e6e6563742d6c6f676f2d343135783236362e706e67)

The screenshot would be awesome! so we can check how they looked like.

**Comment by andymarcus** [comment]
Better if it there was a link to the Internet Archive Wayback Machine page for that site.

**Comment by styfle** [comment]
This list is really overwhelming without the logos. It's a wall of text.
