### ISSUE TITLE
Mr. Jingles

### ISSUE THREAD

**Issue by CaptnCodr** [codyogden/killedbygoogle#255]
**What's the Product's Name?**
Mr. Jingles

**Describe the product in a single sentence.**
Google Notification Widget at the top of several Google products (e.g. Google+, GMail, "New Tab" page, etc.), this button (a little bell) opens a menu with actual notifications to G+, Google Fotos and many more.

**When was the product launched? Provide a specific date, if possible.**
June 2015

**When was the product discontinued? Provide a specific date, if possible.**
7th of March 2019

**Comment by codyogden** [comment]
Link: https://www.androidcentral.com/his-name-mr-jingles
