### ISSUE TITLE
Punchd

### ISSUE THREAD

**Issue by dkirker** [codyogden/killedbygoogle#256]
**What's the Product's Name?**
Punchd

**Describe the product in a single sentence.**
Digital loyalty card app and service targeted towards small businesses.

**When was the product launched? Provide a specific date, if possible.**
Originated 2009 as a student project
Apps in App Store and Play Market (respectively): September 25, 2010, September 13, 2010
Google acquisition: Jully 11, 2011

**When was the product discontinued? Provide a specific date, if possible.**
June 7, 2013

**What type of product was it? App, Service, or Hardware?**
App and Service

**Comment by dkirker** [comment]
Twitter: https://twitter.com/punchd
Homepage (still around with Google acquisition notice!): http://getpunchd.com/

**Comment by frambinni** [comment]
Would you put the acquisition date as date open? Also, I'd consider this as a service because, without the service, there wouldn't be a need for the app.

**Comment by dkirker** [comment]
Hey @codyogden , @frambinni Apologies for not getting back sooner. I created a PR with the addition here: https://github.com/codyogden/killedbygoogle/pull/676 I worded the description to indicate the earlier creation as a student project, and set the dateOpen as the date the team was acquired by Google.
