### ISSUE TITLE
Missing Google Sets

### ISSUE THREAD

**Issue by stephenjbell** [codyogden/killedbygoogle#272]
**What's the Product's Name?**
Google Sets

**Describe the product in a single sentence.**
Given a list of items, Sets would create a list of more items that were similar, which was very useful for brainstorming
More info here: https://searchenginewatch.com/sew/opinion/2111106/rock-the-vote-a-petition-to-bring-back-google-sets

**When was the product launched? Provide a specific date, if possible.**
2002

**When was the product discontinued? Provide a specific date, if possible.**
Mid-2011

**What type of product was it? App, Service, or Hardware?**
Service that was part of Google Labs.

**Comment by codyogden** [comment]
Great! I'll get this one added.
