### ISSUE TITLE
Speak2Tweet

### ISSUE THREAD

**Issue by datapharmer** [codyogden/killedbygoogle#276]
https://www.saynow.com

https://techcrunch.com/2011/01/25/google-buys-voice-messaging-startup-saynow/

https://en.m.wikipedia.org/wiki/Speak_To_Tweet

Purchased and then immediately shutdown.

**Comment by codyogden** [comment]
Oooo...this is a cool one. And all the [tweeted links](https://twitter.com/speak2tweet) to voice messages are definitely dead. Nice!
