### ISSUE TITLE
Nexus Q onboard amp

### ISSUE THREAD

**Issue by jbriano-github** [codyogden/killedbygoogle#278]
The killer Nexus Q feature, that has never been replaced, was the onboard amp allowing the device to power a set of speakers. No need to replace your high-end bookshelf speakers with inferior Google Home, Mini, or Max integrated products.

**Comment by codyogden** [comment]
Nexus Q is in the graveyard. Maybe a better description could be written?

https://github.com/codyogden/killedbygoogle/blob/596d60710f251a1e627c5f66c963453ba8714f86/graveyard.json#L586-L593

**Comment by codyogden** [comment]
Resolved in #313
