### ISSUE TITLE
Google Goggles

### ISSUE THREAD

**Issue by devDeclan** [codyogden/killedbygoogle#280]
Google Goggles was an image recognition mobile app used for searches based on pictures taken by handheld devices.

**Comment by codyogden** [comment]
Did you want us to change the description for this entry?

https://github.com/codyogden/killedbygoogle/blob/596d60710f251a1e627c5f66c963453ba8714f86/graveyard.json#L130-L137

**Comment by devDeclan** [comment]
Its okay
