### ISSUE TITLE
Uncle Sam search

### ISSUE THREAD

**Issue by TPS** [codyogden/killedbygoogle#281]
**What's the Product's Name?**
Uncle Sam Search @ https://Google.com/unclesam
**Describe the product in a single sentence.**
Searched only all US & state government websites for query
**When was the product launched? Provide a specific date, if possible.**
November 1999
**When was the product discontinued? Provide a specific date, if possible.**
June 2011
**What type of product was it? App, Service, or Hardware?**
Service

More info @ (of course) https://www.google.com/search?q=google+%22uncle+sam+search%22

**Comment by TPS** [comment]
@codyogden I'm not sure why this was closed w/o being listed.  Was something I submitted incorrect?

**Comment by codyogden** [comment]
@TPS Nothing wrong! Thanks for your issue. I setup a bot to go through and close anything that hasn't had activity in the last 30 days. I don't have the time currently to sort through the issues and add everything myself. :) Feel free to submit a PR if you'd like to add it.

During Hacktoberfest (October) this year, I'll hopefully have enough participants who can add the stuff that was marked Stale today. I'll put a list of Issues together for those participants to have easy PRs for participation.

**Comment by TPS** [comment]
Perhaps setting up [PR template(s)](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository) similar to your issue templates might help us do so?

**Comment by codyogden** [comment]
That's a good idea, but I'm not sure if it will help the actual execution of adding products. The PR template is for the markdown inside the PR content, not the code/data that's being submitted. The [contributing](https://github.com/codyogden/killedbygoogle#contribute) documentation for adding a product to the list is as simple and straightforward as I hope I could make it.
