### ISSUE TITLE
Missing: Lively

### ISSUE THREAD

**Issue by Journeyman05** [codyogden/killedbygoogle#283]
https://googleblog.blogspot.com/2008/07/be-who-you-want-on-web-pages-you-visit.html?m=1
Introduced in 2008 as a way to embed a second life-like experience of a 3D room into web sites.

**Comment by codyogden** [comment]
Thanks! Lively is already in the graveyard!

![Screenshot of Killed by Google](https://cjo.me/1p9qI7ok78J9RCxs.png)
