### ISSUE TITLE
Add base colour to fix issues with dark themes.

### ISSUE THREAD

**Issue by tmtvl** [codyogden/killedbygoogle#284]
When viewing the content while using Firefox with a dark GTK theme the site is unreadable due to only the background colour being defined.

**Comment by codyogden** [comment]
@tmtvl Good suggestion. Can you let me know if this build preview works?

https://deploy-preview-285--killedbygoogle.netlify.com/

Thanks!

**Comment by tmtvl** [comment]
That seems to work fine.
