### ISSUE TITLE
Google refine resurrected and funded as open refine

### ISSUE THREAD

**Issue by imontaine** [codyogden/killedbygoogle#286]
Sure it's no longer called Google refine but zombie icons?

**Comment by codyogden** [comment]
haha [We had zombie icons for Halloween.](https://twitter.com/killedbygoogle/status/1053377594517786624)

Google Refine's grave was dug in #196. It's always been an open source project, and other projects have had support dropped or been open sourced like Skymap (#207) and Wave (#1).

**Comment by imontaine** [comment]
Guess you guys were already one step ahead of me :)
