### ISSUE TITLE
Missing Inbox by Gmail

### ISSUE THREAD

**Issue by hugomagallanes** [codyogden/killedbygoogle#287]
Inbox by Gmail
A minimal email-slash-to-do-list client for iOS. 

Launched October 22, 2014
Proudly killed March, 2019

(App)

**Comment by dellow** [comment]
It's on the first row?

**Comment by codyogden** [comment]
We've got it!

https://github.com/codyogden/killedbygoogle/blob/45cea701c5442579702257919f6d1c869db88113/graveyard.json#L42-L49
