### ISSUE TITLE
Suggestion: filter non-google projects?

### ISSUE THREAD

**Issue by silent5am** [codyogden/killedbygoogle#292]
I was wondering if it was possible to allow to seperate Google projects from non-Google projects by filtering the respective group.

Obviously, Google at some point did purchase some of these services, but I think it would be interesting to see how many of these projects were started by Google itself and how many were start-ups or small companies that were later purchased by Google and then killed after that integration.

I feel like this would also provide a rough overview into the origin stories of all these apps/services acquired by Google after the innovation was already done.

Alternatively, it would be nice to have some sort of indicator that provides that information at first glance, e.g. "Project X 2001-2006 (Softwarez X99), 2006-2007 (Google)" or something like that.

**Comment by me2345** [comment]
I totally agree
