### ISSUE TITLE
Add: Flutter App

### ISSUE THREAD

**Issue by v3rm0n** [codyogden/killedbygoogle#293]
**What's the Product's Name?**
Flutter
**Describe the product in a single sentence.**
Control music and movies with gestures.
**When was the product launched? Provide a specific date, if possible.**
2012/03/11
**When was the product discontinued? Provide a specific date, if possible.**
It was acquired by Google in October 2013, app was still up for a while though until it was taken down a bit later.
**What type of product was it? App, Service, or Hardware?**
App

https://flutterapp.com/

**Comment by duduvp** [comment]
@v3rm0n isn't the same?
https://flutter.dev/

**Comment by v3rm0n** [comment]
No

**Comment by arisp8** [comment]
This has been renamed to Project Soli but is still being actively developed: https://atap.google.com/soli/

I'm assuming that Flutter's technology has been used as a foundation for Project Soli. https://flutter.dev/ on the other hand is active as well (as of writing this) and is a cross-platform mobile app development framework.

**Comment by v3rm0n** [comment]
Didn’t know about Soli before, cool!
