### ISSUE TITLE
Android Things non Partner use.

### ISSUE THREAD

**Issue by nekosune** [codyogden/killedbygoogle#296]
**Android Things**

**Android things was Google's public IoT platform.**

**2015**

**12/2/2019.**

**It was software.**

https://android-developers.googleblog.com/2019/02/an-update-on-android-things.html . Does removing from public use to partner only count?

**Comment by kevineaton** [comment]
This hurt my IoT company severely and came out of nowhere. It should be on this list, since it was effectively open to anyone, and they even had seller agreements, and then told us the service was being migrated to internal use only. It should be added.

**Comment by nekosune** [comment]
I was working on a IoT doorbell, with a load of google/android integration stuff, wanted to get a prototype then see about getting it made into a product, it was using firebase heavilly, google assistant, etc, all down the drain
