### ISSUE TITLE
Google Allo - Description Change

### ISSUE THREAD

**Issue by codyogden** [codyogden/killedbygoogle#297]
The current description for Google Allo uses present tense. It should be past tense.

`Google Allo is an instant messaging mobile app by Google. It will be rebranded as Google Chat.`

Maybe something like:

`Google Allo was an instant messaging mobile app for Android, iOS, and Web with special features like a virtual assistant and encrypted mode.`

Relevant JSON line:

https://github.com/codyogden/killedbygoogle/blob/45cea701c5442579702257919f6d1c869db88113/graveyard.json#L21

**Comment by NotARossFan** [comment]
I created a branch to address the description changes, but I'm getting a "you don't have permission to access this repository" when I try to publish the branch/make a pull request. Any thoughts?

**Comment by codyogden** [comment]
Not sure? You should be able to open a PR from your master branch into mine. Try this link:

https://github.com/codyogden/killedbygoogle/compare/master...NotARossFan:master
