### ISSUE TITLE
Why not suggest an alternative product ?

### ISSUE THREAD

**Issue by witamine** [codyogden/killedbygoogle#298]
Under each product killed by Google, you could add alternative products (open source ?)

**Comment by ozskywalker** [comment]
-1 ... I don't think that's really the goal of the page here, and how do you include the right ones when in some cases there are so many replacements? 

(i.e. Google Reader dying and spawning 100s of replacements, and not have this devolve into "X is the only tool because it's my favorite" )

**Comment by codyogden** [comment]
I love this idea, and there are a lot of sites out there that have this feature. I have to agree with @ozskywalker for this project. Adding alternatives becomes an arms race of which one is better. I feel it serves others better as a source of free and open information.

From a technical standpoint, we maintain the data by hand in `graveyard.json`. While that will continue to be easily maintainable for the foreseeable future, adding a new data point creates more maintenance.

**Comment by kayvonkamyar** [comment]
Alternatively.net
