### ISSUE TITLE
App Inventor - July 2010 - Dec 2011

### ISSUE THREAD

**Issue by imagnity** [codyogden/killedbygoogle#301]
**What's the Product's Name?**
App Inventor for Android
**Describe the product in a single sentence.**
A visual programming system/application that makes it easy for learners to create mobile apps for Android smartphones without writing any code.
**When was the product launched? Provide a specific date, if possible.**
Released for public in December 2010
**When was the product discontinued? Provide a specific date, if possible.**
Google stopped supporting the system in December 2011 and funded MIT to carry on from there
**What type of product was it? App, Service, or Hardware?**
App

https://en.wikipedia.org/wiki/App_Inventor_for_Android

https://www.androidcentral.com/google-app-inventor-killed-google-labs-will-live-open-source-code

**Comment by imagnity** [comment]
App Inventor for Android—a visual programming system that makes it easy for learners to create mobile apps for Android smartphones without writing any code. This was released for public in December 2010. Google stopped supporting the system in December 2011 and funded MIT to carry on from there.

[https://en.wikipedia.org/wiki/App_Inventor_for_Android](https://en.wikipedia.org/wiki/App_Inventor_for_Android)

[https://www.androidcentral.com/google-app-inventor-killed-google-labs-will-live-open-source-code](https://www.androidcentral.com/google-app-inventor-killed-google-labs-will-live-open-source-code)

**Comment by JasonHK** [comment]
App Inventor is still being maintained by MIT, so I don't think it should count as "killed".
