### ISSUE TITLE
Nik Collection

### ISSUE THREAD

**Issue by kimbami** [codyogden/killedbygoogle#303]
**What's the Product's Name?**
Nik Collection

**Describe the product in a single sentence.**
Photo editing software

**When was the product launched? Provide a specific date, if possible.**
September 2012 (acquisition)

**When was the product discontinued? Provide a specific date, if possible.**
October 25, 2017

**What type of product was it? App, Service, or Hardware?**
App

Reference: https://en.wikipedia.org/wiki/Nik_Software

**Comment by codyogden** [comment]
This project is not dead. Google let it go unsupported for a while, but DXO acquired it and rebooted its development. Someone talked about this product on Twitter today and provided this link: https://www.digitaltrends.com/photography/the-nik-collection-lives-on-with-dxo-labs-update-but-at-a-cost/
