### ISSUE TITLE
Fusion table will be "was" only in Dec 2019

### ISSUE THREAD

**Issue by mskadu** [codyogden/killedbygoogle#307]
For example, the present blurb reads 

> "Off with their heads!" in 8 months, Google Fusion Tables was a web service for 
> data management that provided a means for visualizing data in different charts, 
> maps, and graphs. It was over 10 years old.

This could be dealt with differently by prefixing a different vein of remarks. It will help increase the effect value - maybe?

**Comment by codyogden** [comment]
Combining this into #309
