### ISSUE TITLE
Sky Map is falsely claimed as dead

### ISSUE THREAD

**Issue by Phoenix616** [codyogden/killedbygoogle#316]
Sky Map is listed as being killed while in reality the project [lives on](github.com/sky-map-team/stardroid) under an open source license and supported by the community.

I would like propose that this was at least mentioned or maybe also marked differently than the other dead applications as it is still available and working.

**Comment by codyogden** [comment]
I think

**Comment by lennelei** [comment]
Totally agree! By definition, a project is killed when if it no longer lives which is clearly not the case here.

**Comment by codyogden** [comment]
Ah...cool! Easy PR to delete some lines from `graveyard.json`!

https://github.com/sky-map-team/stardroid
