### ISSUE TITLE
Google I/O game

### ISSUE THREAD

**Issue by Ruben746** [codyogden/killedbygoogle#317]
It was an online game. You had a ball an input and an output and the ball had to enter the output

**Comment by codyogden** [comment]
Thank you for the issue! Games from Google tend to be built for a specific marketing purpose to advertise of show off a feature of another product/service/app. In this case, it was for a specific year of Google I/O. A recent example is the [Carmen Sandiego](https://gamerant.com/where-world-carmen-sandiego-google-game/) featuring Google Earth/Maps. These are fun and memorable items, but I don't consider them on par with a product/service/app release.
