### ISSUE TITLE
Update Google Now description to include Chrome.

### ISSUE THREAD

**Issue by kayvonkamyar** [codyogden/killedbygoogle#318]
google now desktop

Google now desktop was a flag in chrome flags. It added an icon on the taskbar or menubar.

Don’t know both dates. Research them yourself.

Service

**Comment by wToad** [comment]
Google Now is already referenced on the website. The application was probably closed on the same day as the service.

**Comment by codyogden** [comment]
I agree with @wToad. Google Now was the service and it was discontinued across all platforms. One might adjust the description already in the graveyard to call it out.

`Google Now was a feature of Google Search that offered predictive cards with information and daily updates in Chrome and the Google app for Android and iOS.`

https://github.com/codyogden/killedbygoogle/blob/f021fa93dc5a78ebbb1d5150672144919a6202c5/graveyard.json#L1053
