### ISSUE TITLE
Google tasks canvas

### ISSUE THREAD

**Issue by kayvonkamyar** [codyogden/killedbygoogle#338]
google tasks canvas

Google tasks canvas was an website that allows you to use google tasks in fullscreen.

I don’t know when it was launched.

I don’t know ether, I think it’s on April 2 to April 3

Service

**Comment by grant** [comment]
True.

Tasks Canvas is gone, but Tasks is still alive.

Tasks Canvas: http://mail.google.com/tasks/canvas
