### ISSUE TITLE
Google Scribe

### ISSUE THREAD

**Issue by tchoa91** [codyogden/killedbygoogle#354]
**Google Scribe**

Text auto-completion web service. 
“Google Scribe provides text completion service. Using information from what you have already typed in a document, Google Scribe provides related word or phrase completion suggestions. In addition to saving keystrokes, Google Scribe’s suggestions indicate correct or popular phrases to use,”

**Launched:** 2010 (no precise reference found)

**Discontinued:** 2011 or 2012 (no reference found, died with Google labs)

**Type of product:** Web service, part of Google labs

Ref: 
https://itstillworks.com/google-scribe-4200.html
http://2fatdads.com/2010/09/google-scribe-think-of-it-as-t9-for-lappies/

As a French writing in English, it helped me a lot.

Regards

**Comment by tchoa91** [comment]
Why asking for help if you don'y use it?

**Comment by codyogden** [comment]
I appreciate your issue, but I can't dedicate the time to input them all myself. Please feel free to add this to the `graveyard.json` file and open an PR. :) Thank you!
