### ISSUE TITLE
Data Viz / Analysis

### ISSUE THREAD

**Issue by kevbroch** [codyogden/killedbygoogle#357]
Love the site!  I am imagining different data visualizations and analysis of the core data.
Here's timeline using gCharts : https://kevbroch.github.io/goograve/
documented approach here: https://github.com/kevbroch/kevbroch.github.io/tree/master/goograve

**Comment by codyogden** [comment]
This is awesome! I'll update the readme with cool things people are doing with the data.

Thanks for sharing!
