### ISSUE TITLE
Google Pinyin IME for Windows (Chinese IME)

### ISSUE THREAD

**Issue by tiansh** [codyogden/killedbygoogle#358]
**What's the Product's Name?**
Google Pinyin IME (谷歌拼音输入法)

* Wikipedia: [en](https://en.wikipedia.org/wiki/Google_Pinyin) [zh](https://zh.wikipedia.org/wiki/Google%E6%8B%BC%E9%9F%B3%E8%BE%93%E5%85%A5%E6%B3%95)
* Note: Don't be confused with the version for Android which is still available.

**Describe the product in a single sentence.**
A Chinese pinyin IME on Windows.

**When was the product launched? Provide a specific date, if possible.**
April 4, 2007

**When was the product discontinued? Provide a specific date, if possible.**
Latest version is released on June 19, 2014. No official announcement for the discontinue. But the website is down for about 1 year ([since March or April, 2018](https://web.archive.org/web/20180501000000*/http://www.google.com/intl/zh-CN/ime/pinyin)).

**What type of product was it? App, Service, or Hardware?**
Software on Windows OS

**Comment by edwardchanjw** [comment]
I am gonna to vote this up, recommend it. 

This IME is the best of the Chinese world, although there is some good heart/honest IME from Asian [From this list](https://www.zhihu.com/question/19555813) but really sad Google just killed it, without open source it...

**Comment by tiansh** [comment]
Google Japanese IME (Google 日本語入力) may be discontinued too. The website https://www.google.co.jp/intl/ALL_jp/ime/index.html is still available, but clicking download button (Windows 版をダウンロード / MAC 版をダウンロード) result in an 404 page.
