### ISSUE TITLE
Google Wallet card

### ISSUE THREAD

**Issue by scottyhoffo** [codyogden/killedbygoogle#369]
**What's the Product's Name?**
Google Wallet card
**Describe the product in a single sentence.**
Physical card that was issued by Google for use with Google Wallet app.
**When was the product launched? Provide a specific date, if possible.**
Cards issued around 2015.
**When was the product discontinued? Provide a specific date, if possible.**
Card support ended 2016.
**What type of product was it? App, Service, or Hardware?**
Hardware

**Comment by andrewjmetzger** [comment]
***Some additional information:***

Although there is no exact date, the Wallet Card reportedly began its life [around March 2014](https://www.greenbot.com/article/2105387/the-google-wallet-card-can-be-your-free-reloadable-prepaid-debit-card.html). 

Support ended [2016-06-30](https://www.cnet.com/how-to/google-ending-support-for-wallet-cards/).

Here is the [relevant Wikipedia article](https://en.wikipedia.org/wiki/Google_Pay_Send).

**Comment by andrewjmetzger** [comment]
@codyogden 

Sorry, I couldn't track down exact dates.

What else needs adding before Wallet Card meets the criteria for inclusion?

**Comment by codyogden** [comment]
No worries! In #551 I'm going to organize any product issues that were marked stale for Octoberfest where we'll have more eyes/participants to make PRs with data.
