### ISSUE TITLE
Soli

### ISSUE THREAD

**Issue by HawkenKing** [codyogden/killedbygoogle#370]
**What's the Product's Name?**
Soli

**Describe the product in a single sentence.**
Radar wearable chip

**When was the product launched? Provide a specific date, if possible.**
2015

**When was the product discontinued? Provide a specific date, if possible.**
2015

**What type of product was it? App, Service, or Hardware?**
Hardware

**Comment by HawkenKing** [comment]
https://arstechnica.com/gadgets/2019/01/googles-project-soli-radar-gesture-chip-isnt-dead-gets-fcc-approval/

**Comment by 59e5aaf4** [comment]
Killed around 2023 apparently https://web.archive.org/web/20230104030042/https://atap.google.com/soli/ works and later in the year it's a 302 to Google. It never made it to a real product except some Pixel 4 version and for some reason (???) Pokémon is marked as a copyright holder ?

> 1 Pixel 4’s Soli implementation does not include all capabilities and interactions described here.
> 
> 2 Soli functionality is only available on Pixel 4 and only in the US, Canada, Singapore, Australia, Taiwan, Japan and most European countries. For more information see [g.co/pixel/motionsense](https://web.archive.org/web/20230104030042/https://support.google.com/pixelphone/answer/9517454?p=motion_sense&visit_id=637798136820888210-2913946372&rd=1).
> 
> 3 Soli Sandbox is only available on Pixel 4 and only in the United States, Canada, Germany, Spain, Italy, Netherlands, United Kingdom, Ireland, Denmark, France, Taiwan, Japan, and Singapore. For more information see [g.co/pixel/motionsense](https://web.archive.org/web/20230104030042/https://support.google.com/pixelphone/answer/9517454?p=motion_sense&visit_id=637798136820888210-2913946372&rd=1). ©2019 Pokémon. TM, ® Nintendo
> 
> 4 Google Nest Hub requires a Wi-Fi network, a nearby electrical outlet, and a compatible (Android, iOS) mobile device. Minimum OS requirements are available at [g.co/home/req](https://web.archive.org/web/20230104030042/https://support.google.com/googlenest/answer/7035987). iOS is a trademark of Cisco and is used under license.
> 
> 5 Sleep Sensing requires a subscription service. Learn more at [g.co/sleepsensing/preview](https://web.archive.org/web/20230104030042/https://support.google.com/googlenest/answer/10357290). Sleep Sensing features are subject to your permissions and settings. They use motion, sound, and other device and sensor data to work and require placing the device close to the bed and calibrating the device for your sleeping position. Google Assistant, Google Fit app and other Google apps may be required for full functionality. Google Assistant requires a Google Account.
> 
> 6 Device placement and nearby people, pets, or noises can cause inaccurate readings.
> 
> 7 Sleep Sensing feature is not intended to diagnose, cure, mitigate, prevent or treat any disease or condition. Consult your healthcare professional for questions about your health.
