### ISSUE TITLE
Google Palm

### ISSUE THREAD

**Issue by kayvonkamyar** [codyogden/killedbygoogle#377]
**What's the Product's Name?**
Google palm
**Describe the product in a single sentence.**
Google palm was an app and a website. Google.com/palm and google.com/google.pqa
**When was the product launched? Provide a specific date, if possible.**
Dunno
**When was the product discontinued? Provide a specific date, if possible.**
Dunno
**What type of product was it? App, Service, or Hardware?**
App and service

**Comment by codyogden** [comment]
I'm closing this issue for its ow quality as a submission. Providing proper knowledge and information about a product helps our contributors efficiently spend their research time on products.
