### ISSUE TITLE
Google Desktop

### ISSUE THREAD

**Issue by jspeis** [codyogden/killedbygoogle#380]
**What's the Product's Name?**
[Google Desktop](https://en.wikipedia.org/wiki/Google_Desktop)

**Describe the product in a single sentence.**
"Google Desktop was a computer program with desktop search capabilities, created by Google for Linux, Apple Mac OS X, and Microsoft Windows systems."

**When was the product launched? Provide a specific date, if possible.**
October 14, 2004

**When was the product discontinued? Provide a specific date, if possible.**
14 September 2011

**What type of product was it? App, Service, or Hardware?**
Cross-platform Application

(all information sourced from the wikipedia article)

**Comment by codyogden** [comment]
Google Desktop is already on the list. Feel free to PR an updated description if you'd like!

https://github.com/codyogden/killedbygoogle/blob/3c7f3cf49dcd30c51eeb4b3b3faadeecaf6d7b50/graveyard.json#L306-L313
