### ISSUE TITLE
Google Plus

### ISSUE THREAD

**Issue by coolcraftnet18** [codyogden/killedbygoogle#383]
**What's the Product's Name?**
Google plus
**Describe the product in a single sentence.**
Google's social media platform.
**When was the product launched? Provide a specific date, if possible.**
June 28, 2011
**When was the product discontinued? Provide a specific date, if possible.**
April 2, 2019
**What type of product was it? App, Service, or Hardware?**

Website

**Comment by codyogden** [comment]
Google+ is already in the graveyard. :)

Thanks!

https://github.com/codyogden/killedbygoogle/blob/3c7f3cf49dcd30c51eeb4b3b3faadeecaf6d7b50/graveyard.json#L458-L465
