### ISSUE TITLE
reCaptcha Mailhide

### ISSUE THREAD

**Issue by codyogden** [codyogden/killedbygoogle#386]
**What's the Product's Name?**

reCaptcha Mailhide

**Describe the product in a single sentence.**

reCaptcha Mailhide allowed users to mask their email address behind a captcha to prevent robots from scraping the email and sending it spam.

**When was the product launched? Provide a specific date, if possible.**

[2010-04-01](https://web.archive.org/web/20100515000000*/https://www.google.com/recaptcha/mailhide/) unless we can find a more definitive source for the launch date outside of Archive.org.

**When was the product discontinued? Provide a specific date, if possible.**

2018-03-31

**What type of product was it? App, Service, or Hardware?**

service

https://github.com/google/recaptcha/issues/221#issuecomment-409586455

h/t `@francoisrigal` [on Twitter](https://twitter.com/francoisrigal/status/1129860349736431617).

**Comment by ThisIsAccount** [comment]
@codyogden reCAPTCHA Mailhide seems to exist at least since [2007-05-20.](https://web.archive.org/web/20070520042149/http://recaptcha.net/)
“PROTECT YOUR EMAIL” link to Mailhide

(Archive of Mailhide itself appeared on 2007-05-26)
