### ISSUE TITLE
RIP YouTube Gaming

### ISSUE THREAD

**Issue by Primeey** [codyogden/killedbygoogle#416]
**What's the Product's Name?**

[YouTube Gaming](https://support.google.com/youtubegaming/answer/9135119?p=gaming_app_sunset&hl=en&visit_id=636943251738291352-3629697024&rd=1)

**Describe the product in a single sentence.**

YouTube but only Gaming videos.

**When was the product launched? Provide a specific date, if possible.**

August 26, 2015

**When was the product discontinued? Provide a specific date, if possible.**

May 30th, 2019

**What type of product was it? App, Service, or Hardware?**

Service(?)

**Comment by codyogden** [comment]
Thank you!! 🙌 🥇 💯

**Comment by oct2pus** [comment]
This is way late but the Youtube Gaming App had died, the Youtube Gaming web portal [still exists and functions](https://www.youtube.com/gaming). It's even still in the "More from Youtube" Section of the sidebar.
![image](https://user-images.githubusercontent.com/30452393/64134904-c122e480-cda8-11e9-90c5-ccb8b2977964.png)

May want to change the deceased's name to "Youtube Gaming App" and put it under "Apps"
