### ISSUE TITLE
Feature Request: Direct URL / link  for each entry

### ISSUE THREAD

**Issue by vetras** [codyogden/killedbygoogle#436]
This is a feature request, that I'm happy to help implement.
However, first I would like to know what you think and see if anyone else wants this too.

**Feature Draft:**
When we search for a product we should be able to share that search by copying the URL.
The same is valid for a single entry.

**Use Case:**

> Hey mate, heres the link https://killedbygoogle.com/?q=trips
> I told you they were terminating this app!

**Single entry:**
Honestly, I have not taken a look at any source so I don't know if entries have any type of ID.
If they do we could do something like: 
 * https://killedbygoogle.com/?id=27

**Comment by codyogden** [comment]
This is a good idea. When the `graveyard.json` file in production, there is a URL-safe `slug` property added which is based on the name of the product. We could add this as an `id` attribute, so it would be pretty straightforward to implement a direct link (e.g. `#google-plus`).

https://github.com/codyogden/killedbygoogle/blob/153ec0997ac61bac8b2fd38c19dfffb028766458/bin/graveyard#L12-L18

We'd need to:

- [ ] Add a copy link/share button to the front end.
- [ ] Add the `id` attribute using the slug to the specific `<li>`.
- [ ] Update Netlify redirect headers to support direct URLs
