### ISSUE TITLE
Google Pay P2P

### ISSUE THREAD

**Issue by ChildishGiant** [codyogden/killedbygoogle#455]
**What's the Product's Name?**
Google Pay P2P

**Describe the product in a single sentence.**
It allowed people to send money to each other through Google Pay

**When was the product launched? Provide a specific date, if possible.**
Seems to be [around 25/9/18](https://www.digitaltrends.com/mobile/what-is-google-pay/) but this needs to be checked

**When was the product discontinued? Provide a specific date, if possible.**
6 September 2019
![image](https://user-images.githubusercontent.com/13716824/59533737-4acac080-8ee4-11e9-949e-f6dfe0069658.png)

**What type of product was it? App, Service, or Hardware?**
Service

**Comment by codyogden** [comment]
Thanks. Was this service only offered in the UK?

**Comment by ChildishGiant** [comment]
I never personally used the service but I'm from the UK and have used google pay so got this email. It's not clear if the service was only terminated in the UK or only ever existed in the UK. I haven't looked into this yet. Here's a PDF of the email 
[email.pdf](https://github.com/codyogden/killedbygoogle/files/3507329/email.pdf)
