### ISSUE TITLE
Google slate 2 (Google Tablets)

### ISSUE THREAD

**Issue by Mrtomtomon** [codyogden/killedbygoogle#462]
News Google canceled new tablets and discontinued

**Comment by louistsaitszho** [comment]
1) technically no
2) duplicated: https://github.com/codyogden/killedbygoogle/pulls?utf8=%E2%9C%93&q=slate

**Comment by codyogden** [comment]
Yep. This is a dupe. We've now removed Pixel Slate from the list in #517. We'll add it back to the list when Google kills it (stops selling it).
