### ISSUE TITLE
Lightsaber Escape

### ISSUE THREAD

**Issue by DoomTay** [codyogden/killedbygoogle#464]
https://experiments.withgoogle.com/lightsaber-escape

A pretty popular "Chrome Experiment" where you use your phone to control a lightsaber. It was first launched in December 2015 and, according to [Wayback Machine](https://web.archive.org/web/20160801000000*/https://lightsaber.withgoogle.com/) shut down around mid-2016.

**Comment by kayvonkamyar** [comment]
It will close, for reference check #317 and #373.
