### ISSUE TITLE
Google tag manager in index.html

### ISSUE THREAD

**Issue by joha2** [codyogden/killedbygoogle#483]
From my understanding this site offers a list of products or services which were killed or superseded by google products: This implys a certain disenchantment of the site owners on how google dominates the software market. If this is so, I do not understand, why in the `index.html` file, a third-party call to the `googletagmanager.com` is listed, such that google is further fed with data about users visiting this site. From this the world dominating position of google is further supported by the same site owners showing their disenchantment via this site. Is this (the link to GTM) intention or just a mistake?

**Comment by codyogden** [comment]
Initially, I did not have any tracking installed. I decided to add analytics to help understand the long term traffic requirements and understand site performance. This helps guide critical decisions around the project, for example, its hosting requirements. There are no plans to remove GTM at this time.

**Comment by joha2** [comment]
First of all, thanks for your fast response! Anyway I don't understand it completely. Are there no usable open source and more privacy respecting alternatives to analytics and GTM? What about Matomo or Open Web Analytics?

**Comment by codyogden** [comment]
There are certainly usable alternatives, and I understand your concern. The irony of using Google Analytics on a site that seems critical of "the big G" is not lost on me. Using either Matomo or OWA means introducing a fixed, monthly cost for infrastructure hosting which I would have to personally cover.

As a reminder, I do not solicit or accept donations for Killed by Google, nor do I run advertising on Killed by Google. The project is graciously hosted on [Netlify](https://netlify.com)'s free tier where I cover overages personally should the need arise. Overall, this project costs me $1 per month (which is the yearly domain name cost divided by twelve).

Outside of monetary concerns, I feel my time is better spent on the project itself and its marketing. I also don't want to allow the maintenance of add-on infrastructure for this project to pull me away from my other projects. The benefit of maintaining a custom-hosted analytics suite for a single page scroller does not outweigh the cost of the investment of my time.

**Comment by joha2** [comment]
Thanks again for your immediate and detailed answer! From your response I totally understand that you have limited time and the other reasons why you go this way. Anyway with my issue report I did not want to be offensive in this concern and indeed I think your project is a very good one for monitoring and proving how software diversity gets decreased in time due to big monopolies. So keep up the good the work!
