### ISSUE TITLE
Google Photos to Google Drive Sync

### ISSUE THREAD

**Issue by Masterxilo** [codyogden/killedbygoogle#491]
**What's the Product's Name?**
Google Photos to Google Drive Sync

**Describe the product in a single sentence.**
Google Photos and Google Drive will automatically sync your photos and videos.

**When was the product launched? Provide a specific date, if possible.**
May 2015

**When was the product discontinued? Provide a specific date, if possible.**
10 July 2019

**What type of product was it? App, Service, or Hardware?**
Feature of Google Photos and Google Drive.

----

Read the news here:
https://support.google.com/photos/answer/6156103?co=GENIE.Platform%3DAndroid&hl=en-GB
https://support.google.com/photos/answer/9316089
https://www.blog.google/products/photos/simplifying-google-photos-and-google-drive/

![image](https://user-images.githubusercontent.com/2378665/60904357-37a4d980-a273-11e9-8783-7ba724a34f16.png)

**Comment by codyogden** [comment]
Thanks for your Issue! This is an example of a feature, not a standalone product. The easiest way to tell the difference is that this doesn't have its own name or branding.
