### ISSUE TITLE
Google Blog Compass

### ISSUE THREAD

**Issue by captn3m0** [codyogden/killedbygoogle#493]
**What's the Product's Name?** Google Blog Compass

**Describe the product in a single sentence.** Blog Compass helps bloggers manage their sites and find topics to write about based on Google’s trending topics.

**When was the product launched? Provide a specific date, if possible.** 7th Sep 2018

**When was the product discontinued? Provide a specific date, if possible.** 15th June 2019

**What type of product was it? App, Service, or Hardware?** App

News of Birth: https://techcrunch.com/2018/09/06/googles-newest-app-blog-compass-helps-bloggers-in-india-manage-their-sites/

Notice of Death: https://www.androidpolice.com/2019/07/13/google-blog-compass-shutdown/

**Comment by codyogden** [comment]
Thank you! 🙌
