### ISSUE TITLE
Google Android Naming no Longer a desert

### ISSUE THREAD

**Issue by coolcraftnet18** [codyogden/killedbygoogle#554]
**What's the Product's Name?**
Android

**Describe the product in a single sentence.**
Google is no longer using dessert names
**When was the product launched? Provide a specific date, if possible.**
It was named since September 23, 2008
**When was the product discontinued? Provide a specific date, if possible.**
Android Q
**What type of product was it? App, Service, or Hardware?**

OS Name

**Comment by coolcraftnet18** [comment]
https://gizmodo.com/googles-dessert-theme-meets-bittersweet-end-as-android-1837475729

**Comment by codyogden** [comment]
Hah! This is great, but names aren't really a product and don't fit in with the rest of our content. I appreciate the thought though!

**Comment by upintheairsheep** [comment]
Luckily the tradition continues internally

Queen cake
Red velvet cake 
Snow Cone 
Tiramisu
