### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by upintheairsheep** [codyogden/killedbygoogle#558]
Here is an image that explains. 
https://photos.app.goo.gl/MgQCrn85MZqPRCZP8

Here is the code for teh link: 

javascript:(function()%7Bfunction%20RGBtoHSL(RGBColor)%7Bwith(Math)%7Bvar%20R,G,B;var%20cMax,cMin;var%20sum,diff;var%20Rdelta,Gdelta,Bdelta;var%20H,L,S;R=RGBColor%5B0%5D;G=RGBColor%5B1%5D;B=RGBColor%5B2%5D;cMax=max(max(R,G),B);cMin=min(min(R,G),B);sum=cMax+cMin;diff=cMax-cMin;L=sum/2;if(cMax==cMin)%7BS=0;H=0;%7Delse%7Bif(L%3C=(1/2))S=diff/sum;else%20S=diff/(2-sum);Rdelta=R/6/diff;Gdelta=G/6/diff;Bdelta=B/6/diff;if(R==cMax)H=Gdelta-Bdelta;else%20if(G==cMax)H=(1/3)+Bdelta-Rdelta;else%20H=(2/3)+Rdelta-Gdelta;if(H%3C0)H+=1;if(H%3E1)H-=1;%7Dreturn%5BH,S,L%5D;%7D%7Dfunction%20getRGBColor(node,prop)%7Bvar%20rgb=getComputedStyle(node,null).getPropertyValue(prop);var%20r,g,b;if(/rgb%5C((%5Cd+),%5Cs(%5Cd+),%5Cs(%5Cd+)%5C)/.exec(rgb))%7Br=parseInt(RegExp.$1,10);g=parseInt(RegExp.$2,10);b=parseInt(RegExp.$3,10);return%5Br/255,g/255,b/255%5D;%7Dreturn%20rgb;%7Dfunction%20hslToCSS(hsl)%7Breturn%20%22hsl(%22+Math.round(hsl%5B0%5D*360)+%22,%20%22+Math.round(hsl%5B1%5D*100)+%22%25,%20%22+Math.round(hsl%5B2%5D*100)+%22%25)%22;%7Dvar%20props=%5B%22color%22,%22background-color%22,%22border-left-color%22,%22border-right-color%22,%22border-top-color%22,%22border-bottom-color%22%5D;var%20props2=%5B%22color%22,%22backgroundColor%22,%22borderLeftColor%22,%22borderRightColor%22,%22borderTopColor%22,%22borderBottomColor%22%5D;if(typeof%20getRGBColor(document.documentElement,%22background-color%22)==%22string%22)document.documentElement.style.backgroundColor=%22white%22;revl(document.documentElement);function%20revl(n)%7Bvar%20i,x,color,hsl;if(n.nodeType==Node.ELEMENT_NODE)%7Bfor(i=0;x=n.childNodes%5Bi%5D;++i)revl(x);for(i=0;x=props%5Bi%5D;++i)%7Bcolor=getRGBColor(n,x);if(typeof(color)!=%22string%22)%7Bhsl=RGBtoHSL(color);hsl%5B2%5D=1-hsl%5B2%5D;n.style%5Bprops2%5Bi%5D%5D=hslToCSS(hsl);%7D%7D%7D%7D%7D)()

Bye.

**Comment by codyogden** [comment]
Hello! I appreciate your thoughts and effort here. I'm not entirely sure what this code does, but if you'd liked to contribute code to Killed by Google, I would start with the [contributing guide](https://github.com/codyogden/killedbygoogle/blob/master/.github/CONTRIBUTING.md).
