### ISSUE TITLE
Hire by Google

### ISSUE THREAD

**Issue by rtpHarry** [codyogden/killedbygoogle#574]
**What's the Product's Name?**
Hire By Google
https://support.google.com/hire/answer/9460306

**Describe the product in a single sentence.**

**When was the product launched? Provide a specific date, if possible.**

**When was the product discontinued? Provide a specific date, if possible.**

**What type of product was it? App, Service, or Hardware?**

**Comment by codyogden** [comment]
It's already strapped into a guillotine. Thanks! 💯

https://github.com/codyogden/killedbygoogle/blob/0d64a6abf1eefa0c33458f0cb988c24b7e2af94c/graveyard.json#L2-L9
