### ISSUE TITLE
YouTube Leanback

### ISSUE THREAD

**Issue by LaszloEr** [codyogden/killedbygoogle#590]
**What's the Product's Name?**
[Youtube TV](https://www.youtube.com/tv/) (web version)
**Describe the product in a single sentence.**
YouTube TV was a version of YouTube optimized for smart TV web browsers.
**When was the product launched? Provide a specific date, if possible.**
I can't find an exact date, I believe around 2014.
**When was the product discontinued? Provide a specific date, if possible.**
There's no specific date, it only states "soon".
![Screenshot_2019-09-12 YouTube on TV](https://user-images.githubusercontent.com/17292404/64750733-2baaf180-d51a-11e9-8abc-8e23f0447268.png)

**What type of product was it? App, Service, or Hardware?**
Service

**Comment by mpentler** [comment]
I'm not surprised this is going away. Older TVs got shut out of the app, stopped getting updates, and in some cases flat-out refusing to connect when the app was loaded. Older Sony Bravias were dropped a few years ago, and while my current Bravia does work sometimes it often craps out and doesn't load properly.

I suspect it's just a case of not being able to support those older, less capable devices.

**Comment by glaucocustodio** [comment]
I couldn't be more disappointed with this warning.. This version of YouTube has the best watching experience ever.. I will miss it so much :/

**Comment by codyogden** [comment]
We need a `dateClose`. I've been waiting for 9to5Google or other Google-focused tech hub to get a confirmed date from Google.

We need:

- A `dateClose`
- An authoritative source link.
- An accurate name.

Regarding the name: I've seen "leanback" from 9to5Google and Android Police, and "YouTube XL" from Techcrunch (#593). "Leanback" seems like the internal name since it's used in the source code.

```
<div id="leanback"></div>
```

**Comment by codyogden** [comment]
Looks like 9to5Google updated their article on 9/16.

https://9to5google.com/2019/09/16/youtube-leanback-tv-interface-disabled-soon/

**Comment by glaucocustodio** [comment]
I've created a Chrome extension to allow keyboard navigation on youtube.com: https://github.com/glaucocustodio/youcaptain

**Comment by Sunshine-the-eevee** [comment]
there is a extension called YouTube™ for TV and YouTube™ for TV 4K (for 4k support) and ive got them both and im able to use youtube leanback
