### ISSUE TITLE
YouTube XL

### ISSUE THREAD

**Issue by upintheairsheep** [codyogden/killedbygoogle#593]
**What's the Product's Name?**
YouTube XL
**Describe the product in a single sentence.**
YouTube XL is an optimized version of the YouTube site for smart TVs and game consels.
**When was the product launched? Provide a specific date, if possible.**
June 3 2009
**When was the product discontinued? Provide a specific date, if possible.**
June 9, 2013
**What type of product was it? App, Service, or Hardware?**
Service

**Comment by codyogden** [comment]
This is a duplicate of #590
