### ISSUE TITLE
Most of those products transformed to other products inside Google. 

### ISSUE THREAD

**Issue by pooran** [codyogden/killedbygoogle#607]
Most of those products transformed to other products inside Google. Like writely became part of Google docs. We should be highlighting them too.

**Comment by exo-pla-net** [comment]
Indeed, if all features are absorbed by something else, it hasn't been "killed" -- it has been relocated.

ZygoteBody is listed in the graveyard, but here it is [alive and well](https://www.zygotebody.com/). The name was changed from "Google Body", and the app was open sourced.

**Comment by varungupta3009** [comment]
Tez, too, was just rebranded. Everything remained the same. It didn't die. It just changed names.

**Comment by codyogden** [comment]
Yeah. This is a pretty common comment about Killed by Google. But when people describe things being 'transferred', 'transformed', 'migrated', or 'added to' it makes me think about organ donation.

Someone who dies and is an organ donor is no less dead despite pieces of them going to live on in other persons. I'm under the belief that the same applies here. Inbox, for example, died and only specific features moved to Gmail, not all of them.

Regarding Writely and Tez, see #211.

Regarding ZygoteBody, that may be mislabeled, but "Google Body" is still dead. It was added in #154, so a simple PR to correct the name and description may be in order, but that is outside the scope of this issue.
