### ISSUE TITLE
Google Linux Search

### ISSUE THREAD

**Issue by donut87** [codyogden/killedbygoogle#608]
**What's the Product's Name?**
Google Search for Linux
**Describe the product in a single sentence.**
This was a specialized search for Linux related topics.
**When was the product launched? Provide a specific date, if possible.**
Sorry, don't know
**When was the product discontinued? Provide a specific date, if possible.**
Around 2011 I do not have it more specific, but maybe have a look here:
https://www.pcworld.com/article/229774/say_goodbye_to_google_search_portals_for_linux_mac_and_more.html
**What type of product was it? App, Service, or Hardware?**
Service

**Comment by mskadu** [comment]
I think you are referring to Google's "specialized search" service. Also, according to the [the link](https://www.seroundtable.com/google-uncle-sam-13518.html) (dt. Monday, 6th June 2011) that the above article points to, mentions that the support was dropped "over the weekend". This is also backed up by [this](https://www.businessinsider.com/google-cries-uncle-dumps-uncle-sam-vertical-search-but-sam-bounces-back-2011-6?r=US&IR=T) and [this](https://gcn.com/articles/2011/06/15/google-eliminates-uncle-sam-specialized-search-of-government-related-sites.aspx) article. So unless someone comes up with a definitive date, I am going to go with 2011-06-05 as `closeDate`.

**Comment by mskadu** [comment]
Done! I have used Google's launch date for `dateOpen` under the assumption that this feature was present at the very beginning. We can always amend this if newer info comes to light.

**Comment by mskadu** [comment]
Err .. needs to be re-opened 🤔

**Comment by donut87** [comment]
It totally lost track of this one 😅 
But I cannot reopen the issue...
