### ISSUE TITLE
Would name change considered  as killed?

### ISSUE THREAD

**Issue by DDuongNguyen** [codyogden/killedbygoogle#618]
Google wants to change the name of google express to google shopping so im just wondering if thats considered killed?

**Comment by LittleKitacho** [comment]
I think the change has already happened, check Google Play.

**Comment by codyogden** [comment]
Does Google Shopping have the same features as Google Express? I never use either, so I'm not sure. From what I understand, Express was an Amazon Prime competitor (same-day/overnight shipping), and Shopping was always more of a general marketplace.

**Comment by LittleKitacho** [comment]
I don't know if express had overnight shipping, but I could be mistaken (as I am like you: didn't use it much)

I found this great article, anyhow: https://techcrunch.com/2019/09/11/google-express-to-close-in-a-few-weeks-will-become-part-of-google-shopping/

**Comment by DDuongNguyen** [comment]
so I used Google Express before but not Google Shopping. From what I can tell they're identical. They both act as a one-stop shop service for other retails. Besides that Google Shopping has better UI and nothing else as far as I can see

**Comment by LittleKitacho** [comment]
I don't think it would classify as a killing, but a rebranding of a failed service.  And, anyways, Google just silently rebranded it, they didn't include it in their 'spring cleaning' (as far as I know).
