### ISSUE TITLE
Google Brillo

### ISSUE THREAD

**Issue by gustavotemple** [codyogden/killedbygoogle#628]
**What's the Product's Name?**
Google Brillo

**Describe the product in a single sentence.**
Google Brillo was an OS that Google had announced at Google I/O 2015, at its core, Brillo was Android, but it was very different from the standard Android development, Brillo used the coding language C++

**When was the product launched? Provide a specific date, if possible.**
2015-05-28 (Google I/O 2015)

**When was the product discontinued? Provide a specific date, if possible.**
2016-12-13 (Replaced by the Android Things)

**What type of product was it? App, Service, or Hardware?**
App (OS)

**Comment by gustavotemple** [comment]
@codyogden, I sent a PR about this issue.

**Comment by codyogden** [comment]
@gustavotemple No worries! I've been preoccupied at work. I'll get to the PR early next week.
