### ISSUE TITLE
AngularJS

### ISSUE THREAD

**Issue by djfoxer** [codyogden/killedbygoogle#632]
**What's the Product's Name?**
AngularJS

**Describe the product in a single sentence.**
AngularJS was a JavaScript open-source front-end web framework, it was based on MVC pattern with dependency injection technique.

**When was the product launched? Provide a specific date, if possible.**
2010-10-20

**When was the product discontinued? Provide a specific date, if possible.**
2021-06-30

**What type of product was it? App, Service, or Hardware?**
App

**Comment by codyogden** [comment]
Yeah. I'm calling it. Will merge shortly:

- https://www.convective.com/angularjs-end-of-life/
- https://docs.angularjs.org/misc/version-support-status
- https://www.telerik.com/blogs/angularjs-the-final-release

**Comment by codyogden** [comment]
Resolved in #631

**Comment by ray1claw** [comment]
Umm.. But I thought its only being rebranded to Angular. 

I checked the blog to confirm the same and its just a name change and different version control syntax. Doesn't count as killed imho.

**Comment by djfoxer** [comment]
> Umm.. But I thought its only being rebranded to Angular.
> 
> I checked the blog to confirm the same and its just a name change and different version control syntax. Doesn't count as killed imho.

AngularJS !== Angular
Angular is based on TypeScript while AngularJS is 100% JavaScript framework. If you want to move from AJS to Angular2+ you need to... rewrite all your code. You also write apps with Angular 2+ in differnet way. It's why a lot of developers just move from Angular JS directly to React or Vue.js because this frameworks are more stable without unexpected surprises. And if you have to rewrite all from scratch to migrate from AJS to A2+ you could also choose something different, more reliable. New framework was named Angular because Google was afraid of developers that they will be _angry_ because Google had killed AJS... and they are _angry_ - similar name just brings a lot of misunderstanding, as we can see here.

Look at frameworks popularity (watch/star/fork) to see what A2+ losts:
https://github.com/angular/angular
https://github.com/angular/angular.js
https://github.com/facebook/react
https://github.com/vuejs/vue

**Comment by tobmaster** [comment]
There is no need to rewrite and migration pathes are numerous. Most prominent is Microfrontends. 
Imho it really doesn't fit into the picture
