### ISSUE TITLE
Project Abacus

### ISSUE THREAD

**Issue by Pendrokar** [codyogden/killedbygoogle#634]
**What's the Product's Name?**
Project Abacus

**Describe the product in a single sentence.**
> A smartphone authentication method announced in 2015 that aimed to use every sensor in a phone—the front camera, microphone, GPS, touchscreen usage, and more—to continually authenticate a user with a "trust score," alleviating the need for a password.
- [arstechnica article](https://arstechnica.com/gadgets/2019/01/googles-project-soli-radar-gesture-chip-isnt-dead-gets-fcc-approval/)

**When was the product launched? Provide a specific date, if possible.**
Never. Announced in 05-28-2015

**When was the product discontinued? Provide a specific date, if possible.**
2016? Heard nothing since.

**What type of product was it? App, Service, or Hardware?**
Possibly an Android built-in security service.

**Comment by mskadu** [comment]
Given than the product never launched, did it really die? To me, it does not make sense to add it to the list.
