### ISSUE TITLE
Bump

### ISSUE THREAD

**Issue by rogersachan** [codyogden/killedbygoogle#637]
**What's the Product's Name?**
Bump 
**Describe the product in a single sentence.**
A iOS and Android mobile app that enables smartphone users to transfer contact information, photos and files between devices. 
**When was the product launched? Provide a specific date, if possible.**
March 27, 2009
**When was the product discontinued? Provide a specific date, if possible.**
January 31, 2014
**What type of product was it? App, Service, or Hardware?**
App

https://en.wikipedia.org/wiki/Bump_(application)

**Comment by mskadu** [comment]
Already covered (see [here](https://github.com/codyogden/killedbygoogle/blob/68a5c23bda25078c939464a279eb9d6e2765c908/graveyard.json#L587))

**Comment by codyogden** [comment]
I appreciate the issue, @rogersachan! Yep. This one is already in the graveyard. 😄

https://github.com/codyogden/killedbygoogle/blob/68a5c23bda25078c939464a279eb9d6e2765c908/graveyard.json#L586-L593
