### ISSUE TITLE
Website Home page improvement suggestions and questions

### ISSUE THREAD

**Issue by mskadu** [codyogden/killedbygoogle#642]
Hello,

If I can suggest the following improvements to the home page:

1. Pagination: the list continues to steadily grow longer. Can we paginate it in some way? 
2. Count by year died: on similar lines to the type (app/services/hardware/all) breakdown?

And some questions

- Hand vs Little Ghost(?) icon: what drives deciding which one gets used?
- What order is the list displayed in? Perhaps we can move to latest to the oldest?

**Comment by codyogden** [comment]
I'll start with your questions:

> Hand vs Little Ghost(?) icon: what drives deciding which one gets used?

We're currently displaying the Halloween theme until 1 November. It will be reverted to our normal theme when I merge #614. Normally, a [guillotine and tombstone](https://deploy-preview-614--killedbygoogle.netlify.com/) icon are used.

- **Zombie Hand / Guillotine:** Indicates a product's `dateClose` has not passed yet.
- **Ghost / Tombstone:** Indicates a product's `dateClose` has passed.

> What order is the list displayed in? Perhaps we can move to latest to the oldest?

The graveyard is sorted at runtime to display in reverse chronological order of each product's `dateClose`. (Newest killed to oldest killed.)

https://github.com/codyogden/killedbygoogle/blob/456ee20e521455274be01854b12d669d2e582d87/src/App.jsx#L111-L113

---
> Pagination: the list continues to steadily grow longer. Can we paginate it in some way?

There are certainly ways to add pagination on the front end, but the long-scrolling affect is part of the design aesthetic. It both [digitally emulates the iconic US military graveyards](https://www.cem.va.gov/CEM/images/cemphotos/805_calverton.jpg) and ensures there are is little need for user interaction. The latter point is important to ensure the focus is on the content and not figuring out the user interface. The browser's scrollbar provides a natural indicator of space/time to users.

There is also no indication of a [performance issues](https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://killedbygoogle.com) with the current number of entries. As the list of products grows, there may be an opportunity to utilize an endless scrolling effect, but I probably wouldn't make that move until we're greater than 250 products (which is a very arbitrary number).

> Count by year died: on similar lines to the type (app/services/hardware/all) breakdown?

Some 'graveyard stats' information is something I've been considering for a while, but I haven't figured out a good place to fit it into the current content. Less than 2% of users actually engage with the filters at the top, and less than 3% engage with either Search or the filter buttons. 97% of users over the last ninety days scrolled to the footer.

**Comment by mskadu** [comment]
Thanks. 👍
