### ISSUE TITLE
Google Spotlight Stories

### ISSUE THREAD

**Issue by anaanook** [codyogden/killedbygoogle#643]
**What's the Product's Name?**
Google Spotlight Stories
**Describe the product in a single sentence.**
Spotlight Stories was a studio/app/initiative formed to re-imagine VR storytelling.
**When was the product launched? Provide a specific date, if possible.**
October 2013
https://www.cartoonbrew.com/tech/the-revolution-in-interactive-storytelling-has-arrived-and-surprise-google-is-behind-it-97358.html

**When was the product discontinued? Provide a specific date, if possible.**
March 13 2019
https://variety.com/2019/digital/news/google-spotlight-stories-shutting-down-1203163117/
**What type of product was it? App, Service, or Hardware?**
I guess it counts as an app, but was maybe a service?  I'm not sure.  Was a team/studio, so maybe a service?  You can still download the app, but they have discontinued the initiative.

**Comment by mskadu** [comment]
Thanks! This is now done! 😃 

Awaiting merge by @codyogden

**Comment by codyogden** [comment]
Resolved in #644.
