### ISSUE TITLE
Google DayDream VR

### ISSUE THREAD

**Issue by NathanaelA** [codyogden/killedbygoogle#660]
**What's the Product's Name?**
Google DayDream

**Describe the product in a single sentence.**
Virtual Reality Platform for Phones

**When was the product launched? Provide a specific date, if possible.**
Nov 10th, 2016

**When was the product discontinued? Provide a specific date, if possible.**
Oct 15, 2019

**What type of product was it? App, Service, or Hardware?**
Hardware and Software

**Comment by codyogden** [comment]
Hi! Thanks for reporting Daydream! We've already got it on the list.

https://github.com/codyogden/killedbygoogle/blob/48884606089c011d0720bb411fe74621292a7940/graveyard.json#L27-L34
