### ISSUE TITLE
Field Trip

### ISSUE THREAD

**Issue by RohitGhadge** [codyogden/killedbygoogle#662]
Hi,
The Wikipedia page mentions that the app would be shutting down this year (2019) as opposed to what Killed by Google mentions 2015.
https://en.wikipedia.org/wiki/Field_Trip_(application)

**Comment by mskadu** [comment]
Agreed. According to [this blog post](https://nianticlabs.com/blog/fieldtrip/) (Dt. July 12, 2019) by Niantic

> Today, we are announcing that Field Trip will be shutting 
> down service later this year.

and that apps have been already removed from app stores. 

Unfortunately, given it does not specify a particular date - I propose we use Dec 31, 2019 as end date until something specific comes along.  And also use [this article](https://www.engadget.com/2019/07/13/niantic-to-shut-down-field-trip/?guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAKAYUon197aAvgvIoMIJOTWKsnTUpgqsrhxysXpsay1GzZx-zefyle_AibYHG8Jo2rVjAKrpCxg3HDNth4SFKEa3h2IfRZObnPvS7Bh7MsaWTpSWm65y8jy78BOOH2ZYXLwYeWZ7-AzW8cTw_eoSIetgY4q8jnb-Woudjzkh9TTD&guccounter=2) from Engadget (just in case the Niantic blogpost disappears) as source URL.

**Comment by codyogden** [comment]
Already added. Closing.
