### ISSUE TITLE
[Meta, Feature request] Add a way to pay respects, perhaps an F button at each product that places a flower

### ISSUE THREAD

**Issue by davidgro** [codyogden/killedbygoogle#664]
... And have stats on each product for total flowers and flowers per month.

**Comment by ItzMichaelPhillips** [comment]
This is a really good idea lol

**Comment by codyogden** [comment]
This was suggested in #356. It's also a recycled concept from [Slate](http://www.slate.com/articles/technology/map_of_the_week/2013/03/google_reader_joins_graveyard_of_dead_google_products.html).

I don't want to dismiss this idea outright, but it would take a pretty aggressive argument to convince me that adding an auth component, secure API endpoints, client state management, and a stateful database model which then would all need to be maintained indefinitely.

**Comment by gladed** [comment]
Could assign an issue to each item and pull emotes periodically with https://developer.github.com/changes/2016-05-12-reactions-api-preview/. Plus there is something poetic about using an API that has been in beta for four years.

**Comment by codyogden** [comment]
Potentially adding some sort of login/interactive element soon. Closing this for now.
