### ISSUE TITLE
Shutting down Google Cloud Mail Alpha

### ISSUE THREAD

**Issue by srinidhikarthikbs** [codyogden/killedbygoogle#667]
More information about shutting down:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cloudmail-alpha-testers/GRrstFq4oIw/LZaJQLWTCQAJ

**What's the Product's Name?**
Google Cloud Mail Alpha

**Describe the product in a single sentence.**
Cloud Mail was a service offered by Google Cloud Unit (separate from Gmail offered by Google) to support mail-sending use cases while building applications on Google Cloud. 

**When was the product launched? Provide a specific date, if possible.**
This product was released in Alpha a few months back (probably at the beginning of August). I joined late into the Alpha testing program.

**When was the product discontinued? Provide a specific date, if possible.**
Jan 31, 2020

**What type of product was it? App, Service, or Hardware?**
It was an API that basically behaved like the Gmail API, except had a more native feeling like using  Google Cloud APIs and supported Google Cloud authentication methods (Gmail has its own auth methods, given the separation of business units and technologies). I'm sure Gmail APIs can also be used with Google Cloud Auth methods but it is definitely not straightforward.

**Comment by mskadu** [comment]
hi - I am unable to access to the group post because I am not already a member. Are there any other URLs or news report out there to support this? Thanks.

**Comment by codyogden** [comment]
I'm thinking through the current and requested low-level, technical additions to the list. In the mean time, I'm flagging this with a label and will come back to it when I'm ready.

Thanks! I appreciate the suggestions.

**Comment by betobe445** [comment]
I can't access the group , why shutting down such a vital and useful service ?
