### ISSUE TITLE
Add the Build with Chrome Chrome experiment

### ISSUE THREAD

**Issue by ItzMichaelPhillips** [codyogden/killedbygoogle#672]
**What's the Product's Name?**
Build with Chrome
**Describe the product in a single sentence.**
An online LEGO builder where you could make something and place it on a globe alongside others' creations.
**When was the product launched? Provide a specific date, if possible.**
January 2014
**When was the product discontinued? Provide a specific date, if possible.**
March 2019
**What type of product was it? App, Service, or Hardware?**
Service

**Comment by codyogden** [comment]
This was a marketing ploy, not a product. Thanks!
