### ISSUE TITLE
Obituary: Personal Blocklist

### ISSUE THREAD

**Issue by AndrewKvalheim** [codyogden/killedbygoogle#674]
**What's the Product's Name?**

Personal Blocklist

**Describe the product in a single sentence.**

Personal Blocklist was a browser extension that excluded websites of the user's choice from search results.

**What type of product was it? App, Service, or Hardware?**

App

---

Just opening an issue as I couldn't find exact dates or a good source about it. Maybe someone else will be more successful at researching it.

  - The [official page](https://chrome.google.com/webstore/detail/personal-blocklist-by-google/nolijncfnkgaikbjbdaogikpmpbdcdef) for the extension just returns a 404 now.
  - I found various comments referring to it as early as February 2011.
  - The [history](https://web.archive.org/web/20100322191522/https://www.ghacks.net/2010/03/18/blacklist-google-search-results-in-google-chrome/) of [this article](https://www.ghacks.net/2010/03/18/blacklist-google-search-results-in-google-chrome/) suggests that the extension might have existed as early as March 2010 under the name "Google Blacklist" in the Chrome Extensions Gallery.
  - In as early as March 2018 comments start saying that the extension has stopped functioning correctly.
  - In November 2018 someone remarks that it's still listed in the Chrome Web Store despite being defunct.

**Comment by mskadu** [comment]
A bit more research on my end turned up the following:

* This Mashable [article](https://mashable.com/2011/03/10/google-search-block/?europe=true) (Dt 10th March 2011) mentioning that this extension had been released last month. So I am guessing it's safe to say that the release date of the Chrome extension is Feb 2011
* However, the same article also links to this Google [post](https://googleblog.blogspot.com/2011/03/hide-sites-to-find-more-of-what-you.html) (also Dt. 10th March 2011) to this being introduced as a "feature of the search tool" itself 
* Also, I spotted [this article](https://searchengineland.com/google-finally-discontinues-the-blocked-sites-feature-152885) (Dt. 25th March 2013) reporting that the above feature was discontinued but also mentioning that the only way remaining available is the chrome extension - which indicates that as of the day of the article the extension was available.
* And finally, WaybackMachine (web.archive.org) does have snapshots as late as 19th July 2019.

This was all I could find so far ..

Suggested next action:  More information required before implementation

**Comment by RAIDrecovery** [comment]
> Personal Blocklist was a browser extension that excluded websites of the user's choice from search results.

Adding this comment for those, who might be looking for an alternative. 
[Firefox uBlacklist add-on](https://addons.mozilla.org/en-US/firefox/addon/ublacklist/) is still available and works well. It also supports patterns and regular expressions.
