### ISSUE TITLE
Google Pixel 1 EOL

### ISSUE THREAD

**Issue by DusterTheFirst** [codyogden/killedbygoogle#675]
**What's the Product's Name?**
Google Pixel 1

**Describe the product in a single sentence.**
Android smartphones designed, developed and marketed by Google.

**When was the product launched? Provide a specific date, if possible.**
October 4, 2016

**When was the product discontinued? Provide a specific date, if possible.**
Feature updates ceased in October 2018 and security updates lasted for another year, ending in October 2019.

**What type of product was it? App, Service, or Hardware?**
Hardware

**Comment by codyogden** [comment]
Hah! Thanks for the issue! I just talked about this in my comment in #673. :)

Basically, we'll follow a pattern we established in #221 that consolidates phones/tablets into a single entry when the leave the Pixel brand, and add outlier devices with the same brand as separate entries.

Going to close this one, but I appreciate it! (They'll kill Pixel eventually. :P)
