### ISSUE TITLE
Adsense for Mobile

### ISSUE THREAD

**Issue by codyogden** [codyogden/killedbygoogle#678]
**What's the Product's Name?**

Adsense for Mobile

**Describe the product in a single sentence.**

Adsense for mobile was a native application for Android and iOS that allowed users to view and manage aspects of their Adsense account.

**When was the product launched? Provide a specific date, if possible.**

???

**When was the product discontinued? Provide a specific date, if possible.**

???

"Late 2019"

**What type of product was it? App, Service, or Hardware?**

app

Source:

https://ww.9to5google.com/2019/07/15/google-killing-adsense-apps/

**Comment by 0xdeki** [comment]
The Android app was released on the 31st of July in 2013
(https://play.google.com/store/apps/details?id=com.google.android.apps.ads.publisher)

1.0.0 dropped on the app store the 3rd of August same year
(https://apps.apple.com/us/app/google-adsense/id680739529)
