### ISSUE TITLE
The Verge has just done us a big favour!

### ISSUE THREAD

**Issue by mskadu** [codyogden/killedbygoogle#679]
Apologies, I know this isn't a standard request. Just noticed that the verge has just published a list of products Google has killed recently.

Thought I should post it here for us to look through and use

https://www.theverge.com/2019/11/26/20977968/google-graveyard-products-shut-down-dead-not-supported-discontinues-spring-cleaning

**Comment by codyogden** [comment]
Thanks. But they're keyword surfing and it's not even close to comprehensive. Not really useful for us unfortunately.
