### ISSUE TITLE
Code Tests

### ISSUE THREAD

**Issue by codyogden** [codyogden/killedbygoogle#68]
I have only minimal experience writing code tests in React. Not sure if it is worth it for a project this small, but it would be interesting to see some basic code tests implemented.

Open to suggestions, but I'm not setting expectations or assumptions. I may try to do this myself.

**Comment by mlukjanska** [comment]
@codyogden Had some fun adding the tests :) Turns out it's not that easy with styled components - details in the pull request above. Btw - cool project.

**Comment by codyogden** [comment]
@mlukjanska Your PR is amazing! I'll leave a comment there about merging, but thank you **so much** for your testing contributions. 💯 🙌 🙇
