### ISSUE TITLE
Game Builder - This might be a new record

### ISSUE THREAD

**Issue by johnvilsack** [codyogden/killedbygoogle#680]
**What's the Product's Name?**

Google Game Builder

**Describe the product in a single sentence.**

A multiplayer 3D game environment that was a tool for creating new game experiences without coding experience

**When was the product launched? Provide a specific date, if possible.**

June 13, 2019

https://www.blog.google/technology/area-120/create-3d-games-friends-no-experience-required

**When was the product discontinued? Provide a specific date, if possible.**

November 7, 2019

https://steamcommunity.com/games/929860/announcements/detail/1608276251516057010

**What type of product was it? App, Service, or Hardware?**

App with backend service attached

**Comment by mskadu** [comment]
My Vote: No 👎 

According to the second [link](https://steamcommunity.com/games/929860/announcements/detail/1608276251516057010) above
>  ending development of Game Builder and releasing the app and its source code on GitHub!

Clearly only the ownership/ responsibility of the project has changed. That is quite different to say the product is dead.

Suggested next action: Close

**Comment by jrr** [comment]
My Vote: Yes 👍

It was an app that was available to users, and now it's gone.

Does it matter if (most of) it has been open-sourced?

They didn't hand it off to another owner. They pulled the Steam app, and made the (respectable) gesture of publishing the source.

As Google shutdowns go, this isn't a particularly controversial or surprising one (coming out of the experimental "Area 120" group), but it seems like it still qualifies. (unless perhaps you want to give Area 120 projects a free pass)

**Comment by codyogden** [comment]
We've added plenty of other projects that have similar Build->Deprecate by OSSing it. Sky Map and Wave are two I know off the top of my head.
