### ISSUE TITLE
[Feature Request] Categories for Origin

### ISSUE THREAD

**Issue by dleslie** [codyogden/killedbygoogle#685]
It would be nice to be able to see, for instance, the products which originated from within Google versus the products which were bought by Google.

**Comment by codyogden** [comment]
Adding more data is difficult unless I convert to using a database, but that's skill overkill for this project. I appreciate your suggestion! I'm noting this in a backlog, but will close this issue for now.

**Comment by MichaelLHerman** [comment]
I think this would go a long way to show how wasteful google is in addition to its disappointing consumer and developer experience.
