### ISSUE TITLE
Obituary: Google Play Music

### ISSUE THREAD

**Issue by thetechgeek** [codyogden/killedbygoogle#687]
Google Play Music

Music streaming service which also allowed users to upload and stream their own music

November 16, 2011

TBA, but google has announced that it will be discontinued in favor of Youtube Music

Service

Source: [This Interview](https://www.theverge.com/2018/5/23/17386752/youtube-music-uploads-feature-google-play-music) with The Verge. Specifically, they mention migrating all Google Play Music users to Youtube Music once the 2 services achieve feature parity. The article mentions 2019 as a date for the shutdown and transition, but it seems unlikely that deadline will be hit.

**Comment by mskadu** [comment]
My Vote: No 👎 

According to the quoted Verge article
> “Nothing will change about Google Play Music in the near future,” Elias Roman, who has been a product manager for both services, told The Verge today.
>
> Google has said that it will give users plenty of notice when it does decide to make big changes.

In other words, Google Play does not have a end date - yet.

Suggested action: Close

**Comment by codyogden** [comment]
Yep. I agree with @mskadu. Closing this. We'll add GPM when they announce an official end-of-life date.
 Thanks!
