### ISSUE TITLE
Prediction API from GCP

### ISSUE THREAD

**Issue by morriswong** [codyogden/killedbygoogle#691]
**What's the Product's Name?**
Prediction API

**Describe the product in a single sentence.**
A prediction api from GCP

**When was the product launched? Provide a specific date, if possible.**
N.A

**When was the product discontinued? Provide a specific date, if possible.**
April 30, 2018

**What type of product was it? App, Service, or Hardware?**
An AI API, rebranded to google ai platfrom

Reference: https://cloud.google.com/prediction/

**Comment by mskadu** [comment]
My Vote: **Yes**

According to [this](https://www.infoq.com/news/2017/06/google-drops-prediction-api/), 
>After May 1st, 2018, Google will no longer provide technical support, further releases, or any API access to the Cloud Prediction API.

which is as good as _killed_. While the product home page ([link](https://cloud.google.com/prediction/)) specifically says
> Cloud Prediction API was shut down on April 30, 2018.

Leaving very little doubt. As for start date, I was unable to find one. I'd suggest using that of GCP itself. Which, according to [this article](https://en.wikipedia.org/wiki/Google_Cloud_Platform) on Wikipedia, is 7th April 2008

Suggested Next step: Implement

**Comment by codyogden** [comment]
Thanks, everyone. I'm thinking through the current and requested low-level, technical additions to the list. In the mean time, I'm flagging this with a label and will come back to it when I'm ready.

I appreciate the suggestions.
