### ISSUE TITLE
YouTube for Google / Sony Smart TV

### ISSUE THREAD

**Issue by woodcockjosh** [codyogden/killedbygoogle#692]
**What's the Product's Name?**
Youtube

**Describe the product in a single sentence.**
YouTube is not supported on the Android operating system for Sony Smart TV

**When was the product launched? Provide a specific date, if possible.**
Somewhere around 2011

**When was the product discontinued? Provide a specific date, if possible.**
Somewhere around 2015

**What type of product was it? App, Service, or Hardware?**
App / Hardward

**Comment by mskadu** [comment]
To me this sounds like what used to be known as [Youtube Leanback](https://variety.com/2019/digital/news/youtube-leanback-tv-pc-interface-october-2-1203337257/) - in essence a TV compatible browser/web-view. Something that's already covered (at [this line](https://github.com/codyogden/killedbygoogle/blob/ee527ecdfc679deed7ba9ff13b996c755a23f0bd/graveyard.json#L77) in the code, if you are interested). Further URLs (which I was unable to find) might come in handy to help decide.

Suggested next step:  Need more information.

**Comment by codyogden** [comment]
This was Leanback.
