### ISSUE TITLE
Should we add Polymer Library?

### ISSUE THREAD

**Issue by armujahid** [codyogden/killedbygoogle#693]
[Polymer Library](https://github.com/Polymer/polymer) is google's original web component library. At Google I/O 2018 google announced a new Web Component base class, LitElement, as a successor to the Polymer library. So currently polymer library is in maintenance phase and is not recommended for new development. Should we add it in this list?

```
{
    "dateClose": "<in maintenance phase>",
    "dateOpen": "2015-05-29",
    "description": "Google's original web components library",
    "link": "https://polymer-library.polymer-project.org/",
    "name": "Polymer Library",
    "type": "service"
}
```

**Comment by mskadu** [comment]
My vote: **No**

There's no fixed end date in sight - neither has one been announced (that I could find). Unless we can find a cite that specifically shows that Polymer has an end date (or a period eg. late 2020) in sight, we should NOT add it.

Suggested next action: Close
