### ISSUE TITLE
Google Chromecast Audio

### ISSUE THREAD

**Issue by Maartenwut** [codyogden/killedbygoogle#697]
**What's the Product's Name?**
Chromecast Audio
**Describe the product in a single sentence.**
An audio streaming device that lets you stream audio to any speaker using a 3.5mm audio jack, making the speaker essentially wireless.
**When was the product launched? Provide a specific date, if possible.**
September 29, 2015
**When was the product discontinued? Provide a specific date, if possible.**
January 11, 2019
**What type of product was it? App, Service, or Hardware?**
Hardware

**Comment by mskadu** [comment]
Hello and thank you for your suggestion. It would appear this is already covered (see [here](https://github.com/codyogden/killedbygoogle/blob/ee527ecdfc679deed7ba9ff13b996c755a23f0bd/graveyard.json#L154) for the exact code line, if that interests you). 

Suggested next action: Close issue
