### ISSUE TITLE
Should Google Maps for Apple Watch be listed ?

### ISSUE THREAD

**Issue by wolruf** [codyogden/killedbygoogle#698]
**What's the Product's Name?**
Google Maps for Apple Watch series

**Describe the product in a single sentence.**
Google Maps on your wrist

**When was the product launched? Provide a specific date, if possible.**
September 2015 according to https://www.lifewire.com/google-maps-arrives-for-apple-watch-156667

**When was the product discontinued? Provide a specific date, if possible.**
early 2017

**What type of product was it? App, Service, or Hardware?**
App

**Comment by mskadu** [comment]
My vote: No.
Why: According to [this article](https://www.lifewire.com/google-maps-arrives-for-apple-watch-156667) (Dt. Nov 2019)
> However, Google clearly expects to return the app to the Apple Watch at some time in the future. 

which implies the support is suspended. We can consider adding it if/when we have a definitive cite showing Google has definitively killed the app.

Suggested next action: Close (for now).

**Comment by unbeatable-101** [comment]
No, it exists now
