### ISSUE TITLE
AI.API killed by google is missing

### ISSUE THREAD

**Issue by HarisSpahija** [codyogden/killedbygoogle#699]
**What's the Product's Name?**
AI.API

**Describe the product in a single sentence.**
AI.API used to be a chat ai api for webservices

**When was the product launched? Provide a specific date, if possible.**
2010

**When was the product discontinued? Provide a specific date, if possible.**
10 October 2017

**What type of product was it? App, Service, or Hardware?**
Formerly one of the greatest free tools to create voice and chat services for customer support. Currently it is stuck behind a paywall for commercial use and killed by Google

**Comment by HarisSpahija** [comment]
The product currently lives forth as DialogFlow, but hasn't had a major release since https://cloud.google.com/dialogflow/docs/release-notes

**Comment by codyogden** [comment]
I'm working through what lower-level technology additions might look like. I'll return to this when I've figured this out. Flagged with a label for now.

Thank you! I appreciate your issue!

**Comment by HarisSpahija** [comment]
Issue can be closed due to inactivity

**Comment by HarisSpahija** [comment]
Added https://web.archive.org/web/20210701153646/https://chatbase.com/documentation/docs-overview
