### ISSUE TITLE
Suggestion: add a "web API" category

### ISSUE THREAD

**Issue by web-padawan** [codyogden/killedbygoogle#702]
There are some web APIs that have been only implemented in Chrome and actively used but then abandoned, deprecated and eventually removed.

I would like to suggest adding a category for those APIs. Note, they are not actually killed by Google itself, but rather by the lack of community adoption and other browser vendors resistance.

## Motivation

Shipping and pushing opinionated web API without reaching the consensus with other browser vendors has caused a lot of controversy and resulted in negative impact on the ecosystem.

## Candidates

These are few candidates I'm aware of:

### Object.observe

https://chromestatus.com/features/6147094632988672

Originally shipped in Chrome 36, deprecated in 49, and eventually removed in 50.
It was one of the APIs behind Polymer project, used by Polymer 0.5 and before.

### CSS `@apply` rule

https://chromestatus.com/features/5753701012602880

This API was only implemented behind a flag and never released. But it was actively used by Polymer library (1 and 2) and recommended as an approach for styling. [Abandoned](https://www.xanthir.com/b4o00) in 2017.

### HTML Imports

https://chromestatus.com/features/5144752345317376

Originally shipped in Chrome 36. Deprecated in Chrome 70 and will be removed in Chome 80.
This API was heavily used by Polymer library from 0.5 up until 2.

**Comment by codyogden** [comment]
Thanks. I'm thinking through the current and requested low-level, technical additions to the list. In the mean time, I'm flagging this with a label and will come back to it when I'm ready.

Thanks! I appreciate the suggestions.
