### ISSUE TITLE
Google News print replicas

### ISSUE THREAD

**Issue by wolruf** [codyogden/killedbygoogle#703]
**What's the Product's Name?**
Google News "Print Replicas" (ex-Play Magazines app, ex-Play Newsstand)
**Describe the product in a single sentence.**
Offline copies of digital magazines
**When was the product launched? Provide a specific date, if possible.**
2012
**When was the product discontinued? Provide a specific date, if possible.**
January 2020
**What type of product was it? App, Service, or Hardware?**
Service

Seen here: https://www.androidpolice.com/2020/01/03/google-news-killing-digital-magazines-refunds-subscriptions/

**Comment by mskadu** [comment]
Done. I am using the publication date of [this article](https://www.theverge.com/2012/3/7/2853143/google-play-magazines-audiobooks) as the date this service was introduced. Until something more accurate surfaces, of course.
