### ISSUE TITLE
Scavenger Hunt

### ISSUE THREAD

**Issue by joolima** [codyogden/killedbygoogle#707]
Hello all,

I need some help regarding the name of a specific killed google product (I believe it was killed), the logo of the app/service is of a white and gray dog (a husky, maybe), and I believe it has a blue collar. It may be a messaging app of some sort. Anyone happen to know the name? Thanks in advance

**Comment by kevincuallado** [comment]
I have to say this sounds a lot like Trello; though it's a Kanban service and very much still alive and not related to google 🤔
