### ISSUE TITLE
App Maker shutting down on January 19, 2021

### ISSUE THREAD

**Issue by igoramadas** [codyogden/killedbygoogle#711]
**What's the Product's Name?**
App Maker: https://developers.google.com/appmaker
**Describe the product in a single sentence.**
Business apps your company needs, built by you.
**When was the product launched? Provide a specific date, if possible.**
Around May 2017
**When was the product discontinued? Provide a specific date, if possible.**
January 19, 2021
**What type of product was it? App, Service, or Hardware?**
Service

**Comment by codyogden** [comment]
WIP in #712

**Comment by codyogden** [comment]
Resolved in #712 .
