### ISSUE TITLE
New kill

### ISSUE THREAD

**Issue by rscarlat** [codyogden/killedbygoogle#713]
**What's the Product's Name?**
Google App Maker

**Describe the product in a single sentence.**
Build apps that fill gaps, like accelerating business workflows or scaling internal operations, with G Suite’s low-code development environment.

**When was the product launched? Provide a specific date, if possible.**
November 30, 2016

**When was the product discontinued? Provide a specific date, if possible.**
Disable the editor: April 15, 2020
Shutdown: January 19, 2021

**What type of product was it? App, Service, or Hardware?**
Service

**Comment by codyogden** [comment]
Resolved in #712 .
