### ISSUE TITLE
Google App Maker Obituary 

### ISSUE THREAD

**Issue by gsaprimer** [codyogden/killedbygoogle#714]
**What's the Product's Name?**
Google App Maker

**Describe the product in a single sentence.**
Google App Maker is a low-code application development tool, developed by Google inc. 

**When was the product launched? Provide a specific date, if possible.**
Mid 2016

**When was the product discontinued? Provide a specific date, if possible.**
January 19, 2021

**What type of product was it? App, Service, or Hardware?**
App

https://support.google.com/a/answer/9682494

**Comment by codyogden** [comment]
Resolved in #712 .
