### ISSUE TITLE
Google One Today

### ISSUE THREAD

**Issue by brandongalbraith** [codyogden/killedbygoogle#719]
From email:

> Hello,

> We have an important update to share with you.

> We launched Google One Today seven years ago to help people donate to causes they care about. In the last few years, we have seen donors choose other products to fundraise for their favorite nonprofits.

> As a result, we will shut down One Today on February 6th, 2020.

> New nonprofits will no longer be able to sign up for One Today. The Google One Today app will be turned off, and any open projects will be deleted. We will ensure that 100% of funds donated on One Today prior to February 6th are disbursed to the relevant nonprofits.

> If you have any questions, please feel free to contact the One Today team.

> Thank you for your donations and partnership.

> The Google One Today team

**Comment by codyogden** [comment]
Added in #718. Thank you!!! 🙌 💯🥇
