### ISSUE TITLE
AngularJS is ~Angular v1.0. Angular 2.0 / Angular Material lives on

### ISSUE THREAD

**Issue by katlyn-edwards** [codyogden/killedbygoogle#728]
https://angular.io/guide/releases

https://medium.com/p/a2232707eb7c/responses/show

**Comment by codyogden** [comment]
I'm not sure what the purpose of this issue is, but I'll guess this has something to with listing AngularJS. The difference was overviewed in https://github.com/codyogden/killedbygoogle/issues/632#issuecomment-550171921
