### ISSUE TITLE
Android statues

### ISSUE THREAD

**Issue by upintheairsheep** [codyogden/killedbygoogle#732]
**What's the Product's Name?**
Android statues
**Describe the product in a single sentence.**
They were lawn statues that represented an android version.
**When was the product launched? Provide a specific date, if possible.**
??? (Google it!)
**When was the product discontinued? Provide a specific date, if possible.**
Febuary 2020
**What type of product was it? App, Service, or Hardware?**
???

They got vandalized and not fixed, meaning they are abandoned.

**Comment by codyogden** [comment]
Haha. Thanks. Not a product though. :)
