### ISSUE TITLE
Multiplayer Support in Android Games

### ISSUE THREAD

**Issue by mesterjani** [codyogden/killedbygoogle#734]
**What's the Product's Name?**
Multiplayer API in Play Games Services
**Describe the product in a single sentence.**
An API that enabled real-time and turn-based multiplayer in Android games.
**When was the product launched? Provide a specific date, if possible.**
Around October, 2014
**When was the product discontinued? Provide a specific date, if possible.**
September 16th, 2019
**What type of product was it? App, Service, or Hardware?**
Service

**Comment by codyogden** [comment]
This sounds like a feature, not a product itself?
