### ISSUE TITLE
Google Neighbourly

### ISSUE THREAD

**Issue by Jdreioe** [codyogden/killedbygoogle#742]
**name: Google Neighbourly**

**Description: A hyperlocal social networking platform (in beta (India)) which featured crowd-sourced recommendations for different services**

**dateOpen: 2018-06**

**DateClose: 2020-10-12**

**Link: https://support.google.com/neighbourly/answer/9756228?hl=en&ref_topic=9757368**

**Social networking app**

**Comment by codyogden** [comment]
Resolved in #740
