### ISSUE TITLE
Material Design Lite

### ISSUE THREAD

**Issue by AsyncBanana** [codyogden/killedbygoogle#748]
**What's the Product's Name?**
Material Design Lite ([Website Link](https://getmdl.io))
**Describe the product in a single sentence.**
A material design library for the web
**When was the product launched? Provide a specific date, if possible.**
June 19, 2014
**When was the product discontinued? Provide a specific date, if possible.**
December 21, 2016
**What type of product was it? App, Service, or Hardware?**
Service

**Comment by Alexander01998** [comment]
Is it really dead though? Seems like they just haven't updated it in a while.

**Comment by AsyncBanana** [comment]
It has an official [successor](https://www.material.io/develop/web/docs/migrating-from-mdl), so I think it is dead. Although, I'm not sure if the fact that it has a successor (MD Web) invalidates it.
