### ISSUE TITLE
Google Play Music

### ISSUE THREAD

**Issue by pacbeckh** [codyogden/killedbygoogle#750]
I know there have already been several attempts to get this on the list, but I think the time is finally here :'(

**What's the Product's Name?**
Google Play Music

**Describe the product in a single sentence.**
Music streaming service which also allowed users to upload and stream their own music. Replaced by Youtube music

**When was the product launched? Provide a specific date, if possible.**
November 16, 2011

**When was the product discontinued? Provide a specific date, if possible.**
End of 2020

**What type of product was it? App, Service, or Hardware?**
Service

Source:
https://youtube.googleblog.com/2020/05/youtube-music-transfer-google-play-music-library.html

> For now, users will continue to have access to both services. We want to ensure everyone has time to transfer their content and get used to YouTube Music, so we’ll provide plenty of notice ahead of users **no longer having access to Google Play Music later this year**.

If it's ok, I can create a PR

**Comment by codyogden** [comment]
Google Play Music is already in the database, but the date might need to be updated. I'd suggest starting there. Feel free to open a PR with the date change.
