### ISSUE TITLE
Google Play Music

### ISSUE THREAD

**Issue by TheMatelix** [codyogden/killedbygoogle#751]
**What's the Product's Name?**
Google Play Music

**Describe the product in a single sentence.**
Google Play Music is a music and podcast streaming service and online music locker operated by Google, part of its Google Play line of services

**When was the product launched? Provide a specific date, if possible.**
November 16, 2011

**When was the product discontinued? Provide a specific date, if possible.**
Late 2020

**What type of product was it? App, Service, or Hardware?**
App and Service

https://youtube.googleblog.com/2020/05/youtube-music-transfer-google-play-music-library.html

**Comment by codyogden** [comment]
Google Play Music is already on the list. A date change might be needed.
