### ISSUE TITLE
2 Products: Cardboard and Skymap?

### ISSUE THREAD

**Issue by jonaheschwartz** [codyogden/killedbygoogle#753]
**What's the Product's Name?**
1) Cardboard
2) Skymap

**Describe the product in a single sentence.**
1) Cardboard: Entry-level VR system
2) Skymap: Map of night sky; point phone to sky to identify objects

**When was the product launched? Provide a specific date, if possible.**
1) Cardboard: June 25, 2014
2) Skymap: ~May 10, 2010 (https://youtu.be/p6znyx0gjb4)

**When was the product discontinued? Provide a specific date, if possible.**
1) Cardboard: November ~6, 2019: Became open-source, no longer directly supports
2) Skymap: ~January 20, 2012 (Open sourced, and became a 20% project)

**What type of product was it? App, Service, or Hardware?**
1) Cardboard (App and Hardware)
2) Skymap (App)

**Comment by jonaheschwartz** [comment]
Are we adding these?

**Comment by jonaheschwartz** [comment]
@codyogden Can we add SkyMap (still exists but not owned, run, or managed by Google) and Cardboard

**Comment by codyogden** [comment]
Cardboard is still alive, even if it's on a long road to be killed.

SkyMap was added at one point in #213, and removed in #361 (from #316).

**Comment by codyogden** [comment]
CardBoard has been added. Thanks! Closing.
