### ISSUE TITLE
Accessibility Developer Tools

### ISSUE THREAD

**Issue by Scriptura** [codyogden/killedbygoogle#762]
**What's the Product's Name?**
Accessibility Developer Tools

**Describe the product in a single sentence.**
Accessibility audit and element properties.

**When was the product launched? Provide a specific date, if possible.**
7 Sep 2013 ?

**When was the product discontinued? Provide a specific date, if possible.**
4 March 2018

**What type of product was it? App, Service, or Hardware?**
Extension for Chrome

https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb
https://github.com/GoogleChrome/accessibility-developer-tools

**Comment by codyogden** [comment]
This was implemented directly into Chrome's dev tools, yeah?
