### ISSUE TITLE
Would Google Code-In count

### ISSUE THREAD

**Issue by freemin7** [codyogden/killedbygoogle#770]
**What's the Product's Name?**
Google Code-In

**Describe the product in a single sentence.**
A programming challenge that introduces minors to open source work.

**When was the product launched? Provide a specific date, if possible.**
2010

**When was the product discontinued? Provide a specific date, if possible.**
2020

**What type of product was it? App, Service, or Hardware?**
Programming contest

**Comment by codyogden** [comment]
Sorry. I don't this counts. Specifically, it doesn't fit into the app/service/hardware categories. However, I appreciate your suggestion!
