### ISSUE TITLE
Consumer version of Google Plus and G+ APIs

### ISSUE THREAD

**Issue by sk8rboy** [codyogden/killedbygoogle#772]
**What's the Product's Name?**
Google+ / Google Plus.
**Describe the product in a single sentence.**
Google+ was a social network owned and operated by Google.
**When was the product launched? Provide a specific date, if possible.**
At the date of June 28, 2011 Google+ succeeded Google Buzz.
**When was the product discontinued? Provide a specific date, if possible.**
March 7, 2019 was the date the consumer version along with API were discontinued.
**What type of product was it? App, Service, or Hardware?**
App.

**Comment by codyogden** [comment]
Google+ is already on the list.
