### ISSUE TITLE
".... was ...." should be ".... will have been ...." for products yet to be killed

### ISSUE THREAD

**Issue by khrj** [codyogden/killedbygoogle#774]
For whatever products that aren't killed yet but are yet to be killed, future perfect should be used instead of past tense.

For e.g.

> Turning to ashes in 5 months, Google Hangouts was a communication platform which included messages, video chat, and VOIP features. Execution scheduled "late 2020". It was almost 8 years old

Should be

> Turning to ashes in 5 months, Google Hangouts **will have been** a communication platform which included messages, video chat, and VOIP features. Execution scheduled "late 2020". It **will have been** almost 8 years old

I'm not completely sure as to how this could be implemented, because "was" is part of the description itself. Maybe use a script to substitute words for future-killed products?

Thanks for the awesome project!

**Comment by codyogden** [comment]
I'll let the "was" exist as is. Processing language is overkill for this.
