### ISSUE TITLE
Google app maker link is inaccurate

### ISSUE THREAD

**Issue by Zachinquarantine** [codyogden/killedbygoogle#776]
https://venturebeat.com/2020/01/27/google-will-shut-down-app-maker-on-january-19-2021/ is a better link.

**Comment by codyogden** [comment]
Sorry for the delay. Can you tell me why the Wikipedia link is innacurate?

**Comment by Zachinquarantine** [comment]
the link i posted above might contain more accurate and just **more** info in general.... @codyogden im not sure tho, its up to you

**Comment by Zachinquarantine** [comment]
closed due to inactivity.
