### ISSUE TITLE
Playground AR

### ISSUE THREAD

**Issue by GittyMac** [codyogden/killedbygoogle#778]
**What's the Product's Name?**
Playground AR (Originally AR Stickers)

**Describe the product in a single sentence.**
AR Stickers that are built in to Google Camera.

**When was the product launched? Provide a specific date, if possible.**
December 11, 2017
https://mashable.com/2017/12/11/google-launches-ar-stickers-pixel-phones/

**When was the product discontinued? Provide a specific date, if possible.**
August 20, 2020
https://www.xda-developers.com/google-no-longer-offer-playground-ar-stickers-future-pixel-phones-starting-pixel-4a/

**What type of product was it? App, Service, or Hardware?**
App

**Comment by googleooer** [comment]
I have it on my 2 xl

**Comment by danmullen** [comment]
> 
> 
> I have it on my 2 xl

It still works on older devices but from the Pixel 4a on, it's gone.
