### ISSUE TITLE
Google AdSense (App)

### ISSUE THREAD

**Issue by Alexander01998** [codyogden/killedbygoogle#782]
**What's the Product's Name?**
Google AdSense Mobile (though it's just called "Google AdSense" on the Play Store)

**Describe the product in a single sentence.**
An app to track your Google AdSense earnings on the go.

**When was the product launched? Provide a specific date, if possible.**
July 31, 2013 (source: [Google Play Store](https://user-images.githubusercontent.com/10100202/92421389-9c5e0b80-f178-11ea-92d9-5623f75c83b0.jpg))

**When was the product discontinued? Provide a specific date, if possible.**
"end of 2019" (source: https://www.blog.google/products/adsense/upcoming-changes-adsense-mobile-experience/)

**What type of product was it? App, Service, or Hardware?**
App (Android & iOS)

**Comment by Zachinquarantine** [comment]
bump
