### ISSUE TITLE
Encrypted Search description is misleading

### ISSUE THREAD

**Issue by chloecormier** [codyogden/killedbygoogle#783]
"Killed over 2 years ago, Encrypted Search provided users with anonymous internet searching. It was almost 8 years old."

This links to a section of a Wikipedia article talking about the encrypted.google.com site. As this section indicates, it was never anonymous, it was just a part of their rollout of SSL, so it was an HTTPS-enabled version of the normal Google site. It was killed whenever HTTPS was enabled on the default search page anyways, rendering the dedicated encrypted search page obsolete and redundant.

It's true that SSL makes it anonymous to your ISP, but it was never anonymous to Google and it was never anything particularly special, so the way it's characterized here seems misleading.

**Comment by chloecormier** [comment]
Just saw the replies on #198, disregard this.

**Comment by docilecat** [comment]
ur genitals are misleading u fake womyn @chloecormier 
![2469250-dc8229a3387be6cd1f8603027758abf9 — kopia](https://user-images.githubusercontent.com/107488179/173600812-76e0bcd8-87db-4942-9e82-6f1cff0eddb2.jpg)
