### ISSUE TITLE
Google TV has been resurrected! 

### ISSUE THREAD

**Issue by scottlawrencelawson** [codyogden/killedbygoogle#791]
Today at the Google launch event, Google TV was announced as working on a Chromecast device.

**Comment by leezhiwei** [comment]
The thing is that google TV now is a service. But the previous Google TV is smart TV solutions..

**Comment by codyogden** [comment]
Half true. We'll keep the Google TV listing. It's now been updated to point to the correct Wikipedia article in #807.
