### ISSUE TITLE
The future of Killed by Google

### ISSUE THREAD

**Issue by codyogden** [codyogden/killedbygoogle#792]
Hi everyone! I'm killing Killed by Google. Just kidding!!

### I am opening this issue to signal my intent to rebuild Killed by Google from the ground up.

**I am committed to keeping the Killed by Google list an open source project.** Killed by Google has become a valuable resource for many people from so very many different walks of life: gamers, technologists, VCs, educators, students, academia, journalists, non-profits, for-profits, and consumers. I wrote, "We aim to be a source of factual information about the history surrounding Google's dead projects," and I meant it.

However, **I am expanding Killed by Google.** I'm finally ready to expand beyond a simple, one page list of products. I'm laying groundwork to transform Killed by Google into a resource covering all of Google's products, tracking them across the entire lifecycle from sunrise (launch) to sunset (death). I've been tracking many Google products in a giant spreadsheet for the past couple of years, and it's time to not have it in a spreadsheet anymore.

I'm realizing that my goals for this project require a relational database, and it only makes sense to move Killed by Google's data to a CMS, likely headless WordPress (sorry, haters. That's my jam.). This provides more technical flexibility (e.g. static site generation), as well as a litany of other automation and presentation options.

**So, how will we keep it open source?** We'll keep `graveyard.json` as-is. I don't have the details ironed out, but I have a hunch on how I can ensure the `graveyard.json` is editable by the community while also being hooked up to the CMS (e.g. using GitHub Actions and some `diff` automation-ing on the WordPress side). We'll continue to use this repo (albeit after closing all the old issues and PRs) to manage the actual `graveyard.json` list. Only products on that list will be marked as killed.

In the meantime, over the next month I'll be going through and closing each currently open Issue and PRs and citing this issue as the reason. Do not fear, your issues and suggestions will be appropriately labeled and noted for the rebuild. :)

Finally, **I'd like to thank all of you for helping build Killed by Google.** You've been here since the start (two years ago!), and I'm incredibly honored at the response and general helpfulness of every contributor. I am very excited about the future of Killed by Google.

**Comment by TheGameFreak720** [comment]
If you need help building it from the ground up I can help

**Comment by IacobusKopiirefuto** [comment]
When rebuilding Killed by Google, projects that were able to live on independently form Google should definitely be highlighted.  Issue #893
