### ISSUE TITLE
Chart of Deaths over Time

### ISSUE THREAD

**Issue by sirjamesgray** [codyogden/killedbygoogle#798]
Would be cool to be able to view all this data on a chart, so we could see if there are any trends about when Google killed the most products. Perhaps there's a periodic cycle (killing in the 4th quarter, etc.) or maybe there were a few years where the angel of death was merciful to the product suite.

**Comment by codyogden** [comment]
Thanks for the idea. There's very little visualization that can be done with the data we have. A simple line chart isn't a heavy life. I'll consider for upcoming expansion. Closing this for now.
