### ISSUE TITLE
Google Play Music Manager

### ISSUE THREAD

**Issue by bhavita** [codyogden/killedbygoogle#801]
{
    "dateClose": "2020-09-30",
    "dateOpen": "2011-11-16",
    "description": "Google Play Music Manager was the desktop Music Manager for Google Play Music, primarily used to bulk upload and manage your personal Google Play Music library",
    "link": "https://9to5google.com/2020/09/30/google-play-music-manager-for-windows-is-now-shutting-down/",
    "name": "Google Play Music Manager",
    "type": "app"
  }

**Comment by bhavita** [comment]
#800 
Added for hacktoberfest. Please assign the label.

**Comment by codyogden** [comment]
As with [my comment](https://github.com/codyogden/killedbygoogle/pull/800#issuecomment-714584948) in #800, we'll wrap this under GPM.
