### ISSUE TITLE
Change of google TV Links

### ISSUE THREAD

**Issue by leezhiwei** [codyogden/killedbygoogle#807]
**What's the Product's Name?**
Google TV
**Describe the product in a single sentence.**
First attempts of smart TV solution
**When was the product launched? Provide a specific date, if possible.**
6 Oct 2010
**When was the product discontinued? Provide a specific date, if possible.**
June 2014 (SDK removed from Google's site)
**What type of product was it? App, Service, or Hardware?**
Service

Here's the new link for wikipedia
https://en.wikipedia.org/wiki/Google_TV_(smart_TV_platform)

**Comment by codyogden** [comment]
Resolved in #809. Thanks!
