### ISSUE TITLE
Google Sites Classic (Consumer)

### ISSUE THREAD

**Issue by Zachinquarantine** [codyogden/killedbygoogle#813]
**What's the Product's Name?**
Google Sites Classic
**Describe the product in a single sentence.**
Google Sites Classic was the classic version of Google's Sites service that allowed its users to create no-code websites easily.
**When was the product launched? Provide a specific date, if possible.**
2008-02-28
**When was the product discontinued? Provide a specific date, if possible.**
2020-11-01
**What type of product was it? App, Service, or Hardware?**
Service
Link to source: https://9to5google.com/2020/08/06/google-sets-timeline-for-deprecating-classic-google-sites/

**Comment by Zachinquarantine** [comment]
bump

**Comment by HankFay** [comment]
bump

Classic Google Sites was a great place to produce internal documentation with very low friction.
