### ISSUE TITLE
Google Sound Search

### ISSUE THREAD

**Issue by pjmartorell** [codyogden/killedbygoogle#816]
**What's the Product's Name?**
Google Sound Search widget 

**Describe the product in a single sentence.**
Google Sound Search widget is a widget that lets you rapidly identify a song using your mic 
**When was the product launched? Provide a specific date, if possible.**
I don't know
**When was the product discontinued? Provide a specific date, if possible.**
A few weeks ago I think
**What type of product was it? App, Service, or Hardware?**
An Android widget

**Comment by codyogden** [comment]
This is just now part of the core Google app. https://support.google.com/assistant/answer/7554088?hl=en&co=GENIE.Platform%3DAndroid
