### ISSUE TITLE
Death incoming: Unlimited photo storage

### ISSUE THREAD

**Issue by ChildishGiant** [codyogden/killedbygoogle#819]
https://support.google.com/photos/answer/10100180?p=storagepolicy&visit_id=637407206275610017-3458701075&rd=1

**Comment by upintheairsheep** [comment]
Now that’s another one I’ll definitely grief about.

**Comment by ChildishGiant** [comment]
https://youtu.be/Prr-K12RJxI

**Comment by kirillkirill000** [comment]
poor google. how to download all of my photos and videos from photos? i want to leave to local russian cloud drive with unlimited storage for original photo quality

**Comment by ChildishGiant** [comment]
https://takeout.google.com/ Has an option to export all google photos.

**Comment by ultamatum** [comment]
Apparently anything already up before June 1st won't be counted and anything uploaded from a Pixel won't count towards your storage.

**Comment by owlboy** [comment]
> https://youtu.be/Prr-K12RJxI

Was this unlisted when you posted it here?

**Comment by ChildishGiant** [comment]
iirc, yes. Seems they caught it and saw how it'd seem if people saw it now.

**Comment by codyogden** [comment]
We hate to see it go, but it's not a product. Thanks!
