### ISSUE TITLE
Tour Creator

### ISSUE THREAD

**Issue by ThomasOrlita** [codyogden/killedbygoogle#821]
**What's the Product's Name?**
Tour Creator

**Describe the product in a single sentence.**
Tour Creator makes it easy to build immersive, 360 tours right from your computer.

**When was the product launched? Provide a specific date, if possible.**
Announced May 9, 2018 [source](https://www.blog.google/outreach-initiatives/education/tour-creator-schools-vr/)

**When was the product discontinued? Provide a specific date, if possible.**
June 30, 2021 [source](https://support.google.com/tourcreator)

**What type of product was it? App, Service, or Hardware?**
App

**Comment by codyogden** [comment]
Added in #823.
