### ISSUE TITLE
Chrome Web Store Payments

### ISSUE THREAD

**Issue by Zachinquarantine** [codyogden/killedbygoogle#859]
**What's the Product's Name?**
Chrome Web Store Payments
**Describe the product in a single sentence.**
Chrome Web Store Payments is a service that allowed Chrome Web Store developers to monetize their apps directly from the developer dashboard.
**When was the product launched? Provide a specific date, if possible.**
Late 2009-Early 2010
**When was the product discontinued? Provide a specific date, if possible.**
2021-02-01
**What type of product was it? App, Service, or Hardware?**
Service
Link: https://developer.chrome.com/docs/webstore/cws-payments-deprecation/

**Comment by Zachinquarantine** [comment]
bump

**Comment by codyogden** [comment]
This isn't a product? This is a feature (Payments) of a Product (Chrome Web Store).
