### ISSUE TITLE
Google Go Links (AKA Google Short Links)

### ISSUE THREAD

**Issue by joonas-fi** [codyogden/killedbygoogle#865]
Google's URL shortening service (one of them), with possibly some browser-plugin support for typing `go/<your-link-id>` tied to your own organization's short links (maybe this concept is known as [go links](https://golinks.medium.com/the-full-history-of-go-links-and-the-golink-system-cbc6d2c8bb3)). They also offered you a subdomain, e.g `go.yourdomain.com/your-link-id`.

I tried pretty hard, but couldn't find a public URL for this EOL announcement. To be fair, even coverage of this service's existence is a bit scarce. All I have is this email (below screenshot) and I'm pretty sure it's because I have http://go.xs.fi/ (it's operated by Google) with links added by me previously, here's one public link: http://go.xs.fi/hp_procurve_2626

![image](https://user-images.githubusercontent.com/630151/104811593-56d7dc00-5805-11eb-97af-243c07595b81.png)

Here's a screenshot of the UI:

![image](https://user-images.githubusercontent.com/630151/104811712-1c227380-5806-11eb-928a-bee6cdf88ca9.png)

I couldn't find date when this service was launched (the Medium article I linked to mentions "around 2010" which coincides with some of my links' "last access" being in 2013 and one link I had was to a document originating in 2010 but I can't remember when I created the short link), so I'll leave the date blank in my PR.

I also have to link the URL here because there's not much info on this service. But it was a service that Google offered for me and it annoys me that the "forever" URLs will be breaking.

**Comment by Waffull** [comment]
Anyone have an alternate for this service?  I've used it since it was opened with my domain... many hundreds of links.

Thanks,

**Comment by greek** [comment]
> Anyone have an alternate for this service? I've used it since it was opened with my domain... many hundreds of links.
> 
> Thanks,

@Waffull coincidentally enough, there is a similar service named [GoLinks](https://www.golinks.io/)! same concept, different companies

**Comment by joshuacameron** [comment]
@Waffull [bl.ink](https://www.bl.ink/) is another option too

**Comment by Waffull** [comment]
Thanks for your replies!!!

I ended up using rebrandly.com.  I was able to cut & paste the existing
shortlinks into a Google Spreadsheet and import them right in.  Of all the
options I checked out, rebrandly was the best for my needs.  I'm already
using it with 7 other domains.  One interface for everything and if you
don't have many hundreds of links, it's free.

Marc

**Comment by leoherzog** [comment]
We use this at my employer as well. Tomorrow is the last day that this service will be available.

![](https://i.imgur.com/q18Tkxf.png)

It hasn't supported SSL ever, and I'm surprised it took this long for Google to remember that it existed.

**Comment by margaretjschneider** [comment]
Does anyone know of a contact to check in about data export from this service besides requesting it through the Google Form? 

I requested my data from this service on my personal domain via the provided Google Form exactly a month ago today, when I saw someone talking about it (I missed the single email about it back in January). But I still haven't received the data, and of course now the service is shut down. So I'm concerned I won't be able to get the data anymore at this point. 

I rerequested it today, but I'm curious what others' experience has been in this regard, i.e., whether you ever received your data if you requested it. I wish I had done what Marc did above and at least copied and pasted the data from the web interface.

**Comment by Waffull** [comment]
I had done a select all/copy/paste into a spreadsheet and then imported
that document into rebrandly.  I would suspect at this point it's too late
to get your data.  I was never sent the data, despite having requested it
right after they sent the message.

Good luck.

**Comment by codyogden** [comment]
Resolved in #866

**Comment by connordoner** [comment]
For anyone looking in the future for the EOL announcement, it's at https://support.google.com/a/answer/11568987.
