### ISSUE TITLE
Tilt Brush Shutdown

### ISSUE THREAD

**Issue by aidancomi** [codyogden/killedbygoogle#873]
**What's the Product's Name?**
Tilt Brush by Google
**Describe the product in a single sentence.**
Tilt Brush was a VR painting and drawing app.
**When was the product launched? Provide a specific date, if possible.**
4/5/2016
**When was the product discontinued? Provide a specific date, if possible.**
01/26/2021
**What type of product was it? App, Service, or Hardware?**
App

https://techcrunch.com/2021/01/26/google-open-sources-tilt-brush-vr-software-as-it-shuts-down-the-tools-internal-development/?tpcc=ECTW2020

**Comment by owlboy** [comment]
https://opensource.googleblog.com/2021/01/the-future-of-tilt-brush.html

**Comment by codyogden** [comment]
Tilt Brush is already on the list.
