### ISSUE TITLE
Google photos unlimited storage 

### ISSUE THREAD

**Issue by DeonBerenger2006** [codyogden/killedbygoogle#877]
**What's the Product's Name?**
Google photos unlimited cloud storage 
**Describe the product in a single sentence.**
It give google photos unlimited storage
**When was the product launched? Provide a specific date, if possible.**
May 2015
**When was the product discontinued? Provide a specific date, if possible.**
June 2021
**What type of product was it? App, Service, or Hardware?**
Service

**Comment by owlboy** [comment]
Dupe: https://github.com/codyogden/killedbygoogle/issues/819

**Comment by codyogden** [comment]
Dupe with #819. Not a product. Thank you!
