### ISSUE TITLE
Google Hangouts

### ISSUE THREAD

**Issue by DeonBerenger2006** [codyogden/killedbygoogle#878]
![Screenshot 2021-02-03 120227](https://user-images.githubusercontent.com/69000757/106707848-eb20ac00-6617-11eb-87fd-a87ea18795fc.png)
![Screenshot 2021-02-03 120347](https://user-images.githubusercontent.com/69000757/106707856-ecea6f80-6617-11eb-99db-a19bf6159bf8.png)

**What's the Product's Name?**
Google Hangouts
**Describe the product in a single sentence.**
It was a messaging service like WhatsApp lets you chat using Gmail addresses 
**When was the product launched? Provide a specific date, if possible.**
May 15, 2013
**When was the product discontinued? Provide a specific date, if possible.**
June 2021
**What type of product was it? App, Service, or Hardware?**
App

**Comment by codyogden** [comment]
Hangouts is still not quite dead yet. Will close this until it is officially announced for all users.
