### ISSUE TITLE
Swift for TensorFlow

### ISSUE THREAD

**Issue by palle-k** [codyogden/killedbygoogle#884]
**What's the Product's Name?**
Swift for TensorFlow 

**Describe the product in a single sentence.**
Swift for TensorFlow (S4TF) was a next-generation platform for machine learning with a focus on differentiable programming. 

**When was the product launched? Provide a specific date, if possible.**
2018-04-22

**When was the product discontinued? Provide a specific date, if possible.**
2021-02-12

**What type of product was it? App, Service, or Hardware?**
Service

**Comment by brenhinkeller** [comment]
PR opened: https://github.com/codyogden/killedbygoogle/pull/885

**Comment by codyogden** [comment]
Resolved in #885.
