### ISSUE TITLE
Stadia Games & Entertainment

### ISSUE THREAD

**Issue by mgutt** [codyogden/killedbygoogle#889]
**What's the Product's Name?**
Stadia Games & Entertainment

**Describe the product in a single sentence.**
Game development studio for Google Stadia

**When was the product launched? Provide a specific date, if possible.**
"Late 2019" regarding here:
https://blog.google/products/stadia/games-entertainment-studio-playa-vista/

**When was the product discontinued? Provide a specific date, if possible.**
"coming months", so Q1/Q2 2021 regarding here:
https://blog.google/products/stadia/focusing-on-stadias-future-as-a-platform-and-winding-down-sge/

**What type of product was it? App, Service, or Hardware?**
App/Service?!

**Comment by codyogden** [comment]
Thanks! Despite being a deathly blow, it isn't a product. :)
