### ISSUE TITLE
Google Web Toolkit (GWT)

### ISSUE THREAD

**Issue by TaylorSMarks** [codyogden/killedbygoogle#890]
**What's the Product's Name?**
Google Web Toolkit (GWT)

**Describe the product in a single sentence.**
A set of tools that allows web developers to create and maintain JavaScript front-end applications in Java. 

**When was the product launched? Provide a specific date, if possible.**
May 17, 2006

**When was the product discontinued? Provide a specific date, if possible.**
March 14, 2013

**What type of product was it? App, Service, or Hardware?**
Service

===

Google didn't exactly kill this. They switched it to an open source project and stopped supporting it sometime between March (when they released 2.5.1) and June 2013 (they made the announcement that the transition had been completed). The Open Source community continued to support it with regular releases until 2.7.0 in November 2014, although a 2.8 did come out in October 2016 and 2.9 came out in May 2020.

So... it's hard to pin down when this died. If a 2.10 comes out in 2025, would that indicate that this project isn't exactly dead right now?

Here's the chart showing the project was once far more active than it has been for the past several years:
https://github.com/gwtproject/gwt/graphs/code-frequency

**Comment by codyogden** [comment]
This project is clearly still active and being maintained by Googlers.

**Comment by TaylorSMarks** [comment]
The latest release is still 2.9.0, which will be three years old in May.

Google stopped supporting it in June 2013, nearly 9 years ago.
