### ISSUE TITLE
Highlight open source projects

### ISSUE THREAD

**Issue by IacobusKopiirefuto** [codyogden/killedbygoogle#893]
Many of the project that Google killed off have their source code available under open source permissive license (almost always Apache License 2.0), either because they were developed in the open from the start or their source code was released after their discontinuation. Such project include:

- Science Journal for [Android](https://github.com/googlearchive/science-journal), [iOS](https://github.com/googlearchive/science-journal-ios) and [Arduino](https://github.com/google/science-journal-arduino)
- [Game Builder](https://github.com/googlearchive/gamebuilder)
- [BumpTop](https://github.com/BumpTop/BumpTop)
- [uWeave](https://weave.googlesource.com/weave/libweave/) 

Some of these project, which Google left to die, have active forks and they in fact live on.

- [MyTracks](https://code.google.com/archive/p/mytracks/) has fork [OpenTracks](https://github.com/OpenTracksApp/OpenTracks) (3863 commits, 218 stars, [F-Droid](https://f-droid.org/en/packages/de.dennisguse.opentracks/), [Google Play](https://play.google.com/store/apps/details?id=de.dennisguse.opentracks.playstore), [OpenStreetMaps integration](https://github.com/OpenTracksApp/OSMDashboard), [official website](https://opentracksapp.com/))
- Google Wave continues as [openWeave](https://github.com/openweave/openweave-core) (1826 commits, 190 stars, [official website](https://openweave.io/)). Official website even displays message "Google is committed to advancing racial equity for Black communities", so it seems its still sort of part of Google.
- Password Checkup extension seems to be integrated directly inside [Chromium](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/password_check/android/java/src/org/chromium/chrome/browser/password_check/PasswordCheck.java;l=15?q=Password%20Checkup&ss=chromium) (Sources: [Ars Technica](https://arstechnica.com/gadgets/2019/12/googles-password-checkup-goes-mainstream-is-built-into-chrome-79/), [Google](https://www.blog.google/products/chrome/better-password-protections/))
- ZygoteBody has open sourced [core](https://code.google.com/archive/p/open-3d-viewer/), continues as **proprietary** [project](https://www.zygotebody.com/)
-  [Tilt Brush](https://github.com/googlevr/tilt-brush) has forks [Open Brush](https://github.com/icosa-gallery/open-brush)  (62 commits, 90 stars, [official site](https://openbrush.org/)) and [Silk Brush](https://github.com/msub2/silk-brush/) (port to  WebXR, 40 commits, 26 stars)
- [Sceneform SDK for Android](https://github.com/google-ar/sceneform-android-sdk) fork by [Thomas Gorisse](https://github.com/thomasgorisse/sceneform-android-sdk) (61 commits, 25 stars, [official website](https://thomasgorisse.github.io/sceneform-android-sdk/))
- [SoundStage](https://github.com/googlearchive/soundstagevr) has fork [soundstagevr](https://github.com/plaidpants/soundstagevr) (125 commits, 29 stars)

There is most likely more. I have focused only on projects in Apps category so far.

I believe it would be of great informative value, if killedbygoogle would clearly mark these open sourced projects, provide link to their code as well as names and links to the active forks, where applicable.

Naturally, these changes should be done without changing the current look of the website. Because of that I have multiple proposal on how to highlight these open source and active projects, depending on how big changes you want to make.

# Simple: new type categories

The most important thing is to ability to easily filter open source and active projects. So it might be enough to change the `"type":` to "open source" or "active". In the same way change `"link:"` to the official Archived repository or where applicable to the most active forked project.

# Better: add new fields in json

```
"openSource": "yes|no"
"license": "[License Name]"
"codeLink": "https://official-google-repository.example.com",
"active": "yes|no",
"ActiveLink": "https://active-project-repository-or-website.example.org",
"Activelicense": "[License Name]",
```
It is probably good idea to have two separate license field. `"license:"` for the killed project and `"Activelicense:"` for the active version. For example ZygoteBody, has small core released under Apache but rest is proprietary. It would be hard to fit something like that in a single field.

This information would be added to the end of the description. Here is example with MyTrack

MyTracks

Killed almost 5 years ago, MyTracks was a GPS tracking application for Android which allowed users to track their path, speed, distance and elevation. It was about 7 years old. It was released under [Apache License 2.0](https://code.google.com/archive/p/mytracks/). It is maintained as [OpenTracks](https://github.com/OpenTracksApp/OpenTracks) under Apache License 2.0. 

# Optional: Change tombstone icon

The tombstone is strong part of the website's visual identity so this change is really not necessary, unless you want to make the open source projects to stand out.

If you really wanted to highlight open source and active projects, the tombstone could be change for them with [OSI logo](https://opensource.org/logo-usage-guidelines), which is designed "to mark software licensed under an [OSI Approved License](https://opensource.org/licenses/category)", which includes Google's favourite Apache-2.0 and probably any license which [Google](https://opensource.google/docs/thirdparty/licenses/#notice) would ever use.
Nice black and white version of OSI logo is available from [Simple Icons](https://simpleicons.org/?q=Open%20Source) (under CC0) and  [Font Awesome](https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/brands/osi.svg)  (under [CC BY 4.0](https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt), OSI icon on [official website](https://fontawesome.com/icons/osi?style=brands)). 
Alternatively you could use code something like this Material [code](https://material.io/resources/icons/?search=code&icon=code&style=baseline) ([Apache License 2.0](https://github.com/google/material-design-icons))

For the active project you might use GitHub's [fork icon](https://octicons-primer.vercel.app/octicons/git-fork-24) ([MIT license](https://github.com/primer/octicons)).

The change of icons is not really necessary. Simply ignore this part if you don't like it.

**Comment by codyogden** [comment]
I like this idea a lot. I'm working on some things that could include highlighting if a project is open sourced/has open source code. Specifically, I'm currently standardizing additional links/news/resources/information, and this feels like a great piece I can add into that schema.

**Comment by codyogden** [comment]
I don't see this being added at this point unless I switch to managing products via a database. I'm noting this in a backlog, but will close this issue for now. I appreciate your detailed suggestion. Thank you!
