### ISSUE TITLE
Google WiFi

### ISSUE THREAD

**Issue by shmykelsa** [codyogden/killedbygoogle#913]
**Google WiFi**
Product: Mobile App
Description: App to configure Google OnHub, a line of custom mesh routers.

Both the app and the hardware were launched on 30th of August 2015. With an update on last September, Google Home app gained support for configuring OnHub. 

The app will be discontinued on May 2021

Source: https://9to5google.com/2021/04/02/google-wifi-shutting-down-google-home/

**Comment by codyogden** [comment]
Closing. See my comment in #930,
