### ISSUE TITLE
Did I do the PR correcrly? 

### ISSUE THREAD

**Issue by rifkiamil** [codyogden/killedbygoogle#964]
Sorry for the silly question. Should I be doing the PR from my fork or your repo? https://github.com/rifkiamil/killedbygoogle/pull/1/files.

**Comment by shuuji3** [comment]
@rifkiamil Hello🙂 It looks like that you selected your repository as a target repository. But when creating a PR, normally you need to select this repository, codyogden/killedbygoogle, as a target.

Please consult this document as a reference: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by rifkiamil** [comment]
@shuuji3 In https://github.com/codyogden/killedbygoogle/blob/main/README.md "Finally, create a Pull Request (PR) using the newly created branch (Important: DON'T use the main branch for the PR). Submit it with the necessary explanations." 

It says don't use "main branch for the PR", I can only see the following four. Which would be the correct one to select?

* main
* dependabot/npm_and_yarn/jest-27.0.6
* dependabot/npm_and_yarn/next-11.0.1
* dependabot/npm_and_yarn/date-fns-2.22.1

![Screenshot 2021-07-08 at 23 57 29](https://user-images.githubusercontent.com/1672403/125000459-5b5caf00-e048-11eb-9027-4b0f0c0f9c1f.png)

**Comment by codyogden** [comment]
You did! I made a slight adjustment to your description text. Once the checks pass, I'll merge. Thanks!
