### ISSUE TITLE
💀 Kaleidoscope

### ISSUE THREAD

**Issue by WAZAAAAA0** [codyogden/killedbygoogle#973]
**NAME:** Kaleidoscope
**DESCRIPTION:** streaming service hub
**LAUNCH:** 2020-08-19? (reported to be "in the works since 2019")
**SHUTDOWN:** 2021-01-05 (https://chromium-review.googlesource.com/c/chromium/src/+/2596439/2)
**TYPE:** app?

**Comment by codyogden** [comment]
Good find! But this was never released or launched to anyone outside of Googlers.

https://9to5google.com/2021/01/08/chrome-kaleidoscope-streaming-service/
