### ISSUE TITLE
End of Google posts

### ISSUE THREAD

**Issue by kppnesh** [codyogden/killedbygoogle#978]
Google posts, knowledge panel. 

Knowledge panel/graph is the card comes along search when you search for popular person or band

May 16,2012

July, 2021

Service

**Comment by kppnesh** [comment]
They stopped Google posts entirely and they e revoked permission to change knowledge panel details by ourself. (owner)

**Comment by codyogden** [comment]
Please provide a source link.

**Comment by kppnesh** [comment]
![image](https://user-images.githubusercontent.com/70881773/128618521-b13d62d6-94b2-440d-8352-69ecb867dd20.png)

 I got a mail from google stating the following : 
<html>
<body>


You've received this email because you have used the Posts on Google feature.
--
 
Thank you for using Posts on Google. As we announced earlier, Posts on Google is being discontinued.
 
Beginning on July 20th, 2021, you will no longer be able to create new posts via Posts on Google or use the authoring tool to make updates to the knowledge panel. You will have 30 days from this date to download and save your content. You will still be able to manage your presence on Google by suggesting changes to your knowledge panel directly on Search.
 
As a reminder, this does not affect a similar product available for local businesses and other organizations with physical locations. If you are eligible, you can learn more about posts for local businesses.
 
If you have any questions, please contact us.
 
The Google Search team


</body>
</html>

**Comment by kppnesh** [comment]
![image](https://user-images.githubusercontent.com/70881773/128618602-9026c602-5ce5-4d38-9ca0-05c98863304f.png)
This is the announcement mail for your reference. 
<html>
<body>


You've received this email because you have used the Posts on Google feature.
--
 
Thank you for using Posts on Google.
 
Since we first launched this feature as a pilot program, we've expanded Posts on Google to a variety of individuals and organizations. In this time, we've found that while managing their presence on Google is an important priority for brands and organizations, this specific feature did not prove to be as helpful for users as we had hoped. Therefore, we’ve decided to discontinue Posts on Google.
 
Beginning on July 20th, 2021, you will no longer be able to create new posts via Posts on Google or use the authoring tool to make updates to the knowledge panel. You will have 30 days from this date to download and save your content. You will still be able to manage your presence on Google by suggesting changes to your knowledge panel directly on Search.
 
Please note: this does not affect a similar product available for local businesses and other organizations with physical locations. If you are eligible, you can learn more about posts for local businesses.
 
If you have any questions, please contact us.
 
The Google Search team


</body>
</html>

**Comment by kppnesh** [comment]
Aren't these snaps enough?

**Comment by kppnesh** [comment]
@codyogden pls have a look and close the issue. Gentle reminder incase you missed the issue.

**Comment by codyogden** [comment]
@kppnesh Thanks! I still need an external [source link](https://github.com/codyogden/killedbygoogle#link) in order to add this to the list.

**Comment by codyogden** [comment]
Here's a source link. Will add shortly.

https://www.seroundtable.com/google-posts-knowledge-panels-discontinued-31755.html
