### ISSUE TITLE
Material Design Components for iOS

### ISSUE THREAD

**Issue by StefanOltmann** [codyogden/killedbygoogle#991]
See

https://github.com/material-components/material-components-ios#materials-ios-libraries-are-in-maintenance-mode-as-of-july-15-2021

**What's the Product's Name?**
Material Design Components for iOS

**Describe the product in a single sentence.**
Material Design Components build for iOS

**When was the product launched? Provide a specific date, if possible.**

**When was the product discontinued? Provide a specific date, if possible.**
2021-07-15

**What type of product was it? App, Service, or Hardware?**
Library

**Comment by codyogden** [comment]
I don't quite think this fits editorially with the rest of the entries. Specifically, you noted this was a Library, not one of the current categories. Appreciate the suggestion though!
